// Code generated by ent, DO NOT EDIT.

package poolsettlementline

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the poolsettlementline type in the database.
	Label = "pool_settlement_line"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSettlementID holds the string denoting the settlement_id field in the database.
	FieldSettlementID = "settlement_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUsageWeight holds the string denoting the usage_weight field in the database.
	FieldUsageWeight = "usage_weight"
	// FieldUsageShare holds the string denoting the usage_share field in the database.
	FieldUsageShare = "usage_share"
	// FieldAllocatedCostMinor holds the string denoting the allocated_cost_minor field in the database.
	FieldAllocatedCostMinor = "allocated_cost_minor"
	// FieldContributionCreditMinor holds the string denoting the contribution_credit_minor field in the database.
	FieldContributionCreditMinor = "contribution_credit_minor"
	// FieldAdjustmentMinor holds the string denoting the adjustment_minor field in the database.
	FieldAdjustmentMinor = "adjustment_minor"
	// FieldNetAmountMinor holds the string denoting the net_amount_minor field in the database.
	FieldNetAmountMinor = "net_amount_minor"
	// FieldPaymentStatus holds the string denoting the payment_status field in the database.
	FieldPaymentStatus = "payment_status"
	// Table holds the table name of the poolsettlementline in the database.
	Table = "pool_settlement_lines"
)

// Columns holds all SQL columns for poolsettlementline fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSettlementID,
	FieldUserID,
	FieldUsageWeight,
	FieldUsageShare,
	FieldAllocatedCostMinor,
	FieldContributionCreditMinor,
	FieldAdjustmentMinor,
	FieldNetAmountMinor,
	FieldPaymentStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultUsageWeight holds the default value on creation for the "usage_weight" field.
	DefaultUsageWeight string
	// UsageWeightValidator is a validator for the "usage_weight" field. It is called by the builders before save.
	UsageWeightValidator func(string) error
	// DefaultUsageShare holds the default value on creation for the "usage_share" field.
	DefaultUsageShare string
	// UsageShareValidator is a validator for the "usage_share" field. It is called by the builders before save.
	UsageShareValidator func(string) error
	// DefaultAllocatedCostMinor holds the default value on creation for the "allocated_cost_minor" field.
	DefaultAllocatedCostMinor int64
	// DefaultContributionCreditMinor holds the default value on creation for the "contribution_credit_minor" field.
	DefaultContributionCreditMinor int64
	// DefaultAdjustmentMinor holds the default value on creation for the "adjustment_minor" field.
	DefaultAdjustmentMinor int64
	// DefaultNetAmountMinor holds the default value on creation for the "net_amount_minor" field.
	DefaultNetAmountMinor int64
	// DefaultPaymentStatus holds the default value on creation for the "payment_status" field.
	DefaultPaymentStatus string
	// PaymentStatusValidator is a validator for the "payment_status" field. It is called by the builders before save.
	PaymentStatusValidator func(string) error
)

// OrderOption defines the ordering options for the PoolSettlementLine queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySettlementID orders the results by the settlement_id field.
func BySettlementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUsageWeight orders the results by the usage_weight field.
func ByUsageWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageWeight, opts...).ToFunc()
}

// ByUsageShare orders the results by the usage_share field.
func ByUsageShare(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageShare, opts...).ToFunc()
}

// ByAllocatedCostMinor orders the results by the allocated_cost_minor field.
func ByAllocatedCostMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllocatedCostMinor, opts...).ToFunc()
}

// ByContributionCreditMinor orders the results by the contribution_credit_minor field.
func ByContributionCreditMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContributionCreditMinor, opts...).ToFunc()
}

// ByAdjustmentMinor orders the results by the adjustment_minor field.
func ByAdjustmentMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdjustmentMinor, opts...).ToFunc()
}

// ByNetAmountMinor orders the results by the net_amount_minor field.
func ByNetAmountMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetAmountMinor, opts...).ToFunc()
}

// ByPaymentStatus orders the results by the payment_status field.
func ByPaymentStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentStatus, opts...).ToFunc()
}
