// Code generated by ent, DO NOT EDIT.

package valuationfxrate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the valuationfxrate type in the database.
	Label = "valuation_fx_rate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldBaseCurrency holds the string denoting the base_currency field in the database.
	FieldBaseCurrency = "base_currency"
	// FieldQuoteCurrency holds the string denoting the quote_currency field in the database.
	FieldQuoteCurrency = "quote_currency"
	// FieldRate holds the string denoting the rate field in the database.
	FieldRate = "rate"
	// FieldEffectiveFrom holds the string denoting the effective_from field in the database.
	FieldEffectiveFrom = "effective_from"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCreatedByUserID holds the string denoting the created_by_user_id field in the database.
	FieldCreatedByUserID = "created_by_user_id"
	// Table holds the table name of the valuationfxrate in the database.
	Table = "valuation_fx_rates"
)

// Columns holds all SQL columns for valuationfxrate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldBaseCurrency,
	FieldQuoteCurrency,
	FieldRate,
	FieldEffectiveFrom,
	FieldSource,
	FieldCreatedByUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultBaseCurrency holds the default value on creation for the "base_currency" field.
	DefaultBaseCurrency string
	// BaseCurrencyValidator is a validator for the "base_currency" field. It is called by the builders before save.
	BaseCurrencyValidator func(string) error
	// DefaultQuoteCurrency holds the default value on creation for the "quote_currency" field.
	DefaultQuoteCurrency string
	// QuoteCurrencyValidator is a validator for the "quote_currency" field. It is called by the builders before save.
	QuoteCurrencyValidator func(string) error
	// RateValidator is a validator for the "rate" field. It is called by the builders before save.
	RateValidator func(string) error
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
)

// OrderOption defines the ordering options for the ValuationFXRate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBaseCurrency orders the results by the base_currency field.
func ByBaseCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseCurrency, opts...).ToFunc()
}

// ByQuoteCurrency orders the results by the quote_currency field.
func ByQuoteCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuoteCurrency, opts...).ToFunc()
}

// ByRate orders the results by the rate field.
func ByRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRate, opts...).ToFunc()
}

// ByEffectiveFrom orders the results by the effective_from field.
func ByEffectiveFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveFrom, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCreatedByUserID orders the results by the created_by_user_id field.
func ByCreatedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByUserID, opts...).ToFunc()
}
