// Code generated by ent, DO NOT EDIT.

package valuationfxrate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// BaseCurrency applies equality check predicate on the "base_currency" field. It's identical to BaseCurrencyEQ.
func BaseCurrency(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldBaseCurrency, v))
}

// QuoteCurrency applies equality check predicate on the "quote_currency" field. It's identical to QuoteCurrencyEQ.
func QuoteCurrency(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldQuoteCurrency, v))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldRate, v))
}

// EffectiveFrom applies equality check predicate on the "effective_from" field. It's identical to EffectiveFromEQ.
func EffectiveFrom(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldEffectiveFrom, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldSource, v))
}

// CreatedByUserID applies equality check predicate on the "created_by_user_id" field. It's identical to CreatedByUserIDEQ.
func CreatedByUserID(v int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLTE(FieldUpdatedAt, v))
}

// BaseCurrencyEQ applies the EQ predicate on the "base_currency" field.
func BaseCurrencyEQ(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldBaseCurrency, v))
}

// BaseCurrencyNEQ applies the NEQ predicate on the "base_currency" field.
func BaseCurrencyNEQ(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNEQ(FieldBaseCurrency, v))
}

// BaseCurrencyIn applies the In predicate on the "base_currency" field.
func BaseCurrencyIn(vs ...string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIn(FieldBaseCurrency, vs...))
}

// BaseCurrencyNotIn applies the NotIn predicate on the "base_currency" field.
func BaseCurrencyNotIn(vs ...string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotIn(FieldBaseCurrency, vs...))
}

// BaseCurrencyGT applies the GT predicate on the "base_currency" field.
func BaseCurrencyGT(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGT(FieldBaseCurrency, v))
}

// BaseCurrencyGTE applies the GTE predicate on the "base_currency" field.
func BaseCurrencyGTE(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGTE(FieldBaseCurrency, v))
}

// BaseCurrencyLT applies the LT predicate on the "base_currency" field.
func BaseCurrencyLT(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLT(FieldBaseCurrency, v))
}

// BaseCurrencyLTE applies the LTE predicate on the "base_currency" field.
func BaseCurrencyLTE(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLTE(FieldBaseCurrency, v))
}

// BaseCurrencyContains applies the Contains predicate on the "base_currency" field.
func BaseCurrencyContains(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldContains(FieldBaseCurrency, v))
}

// BaseCurrencyHasPrefix applies the HasPrefix predicate on the "base_currency" field.
func BaseCurrencyHasPrefix(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldHasPrefix(FieldBaseCurrency, v))
}

// BaseCurrencyHasSuffix applies the HasSuffix predicate on the "base_currency" field.
func BaseCurrencyHasSuffix(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldHasSuffix(FieldBaseCurrency, v))
}

// BaseCurrencyEqualFold applies the EqualFold predicate on the "base_currency" field.
func BaseCurrencyEqualFold(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEqualFold(FieldBaseCurrency, v))
}

// BaseCurrencyContainsFold applies the ContainsFold predicate on the "base_currency" field.
func BaseCurrencyContainsFold(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldContainsFold(FieldBaseCurrency, v))
}

// QuoteCurrencyEQ applies the EQ predicate on the "quote_currency" field.
func QuoteCurrencyEQ(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldQuoteCurrency, v))
}

// QuoteCurrencyNEQ applies the NEQ predicate on the "quote_currency" field.
func QuoteCurrencyNEQ(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNEQ(FieldQuoteCurrency, v))
}

// QuoteCurrencyIn applies the In predicate on the "quote_currency" field.
func QuoteCurrencyIn(vs ...string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIn(FieldQuoteCurrency, vs...))
}

// QuoteCurrencyNotIn applies the NotIn predicate on the "quote_currency" field.
func QuoteCurrencyNotIn(vs ...string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotIn(FieldQuoteCurrency, vs...))
}

// QuoteCurrencyGT applies the GT predicate on the "quote_currency" field.
func QuoteCurrencyGT(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGT(FieldQuoteCurrency, v))
}

// QuoteCurrencyGTE applies the GTE predicate on the "quote_currency" field.
func QuoteCurrencyGTE(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGTE(FieldQuoteCurrency, v))
}

// QuoteCurrencyLT applies the LT predicate on the "quote_currency" field.
func QuoteCurrencyLT(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLT(FieldQuoteCurrency, v))
}

// QuoteCurrencyLTE applies the LTE predicate on the "quote_currency" field.
func QuoteCurrencyLTE(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLTE(FieldQuoteCurrency, v))
}

// QuoteCurrencyContains applies the Contains predicate on the "quote_currency" field.
func QuoteCurrencyContains(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldContains(FieldQuoteCurrency, v))
}

// QuoteCurrencyHasPrefix applies the HasPrefix predicate on the "quote_currency" field.
func QuoteCurrencyHasPrefix(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldHasPrefix(FieldQuoteCurrency, v))
}

// QuoteCurrencyHasSuffix applies the HasSuffix predicate on the "quote_currency" field.
func QuoteCurrencyHasSuffix(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldHasSuffix(FieldQuoteCurrency, v))
}

// QuoteCurrencyEqualFold applies the EqualFold predicate on the "quote_currency" field.
func QuoteCurrencyEqualFold(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEqualFold(FieldQuoteCurrency, v))
}

// QuoteCurrencyContainsFold applies the ContainsFold predicate on the "quote_currency" field.
func QuoteCurrencyContainsFold(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldContainsFold(FieldQuoteCurrency, v))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLTE(FieldRate, v))
}

// RateContains applies the Contains predicate on the "rate" field.
func RateContains(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldContains(FieldRate, v))
}

// RateHasPrefix applies the HasPrefix predicate on the "rate" field.
func RateHasPrefix(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldHasPrefix(FieldRate, v))
}

// RateHasSuffix applies the HasSuffix predicate on the "rate" field.
func RateHasSuffix(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldHasSuffix(FieldRate, v))
}

// RateEqualFold applies the EqualFold predicate on the "rate" field.
func RateEqualFold(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEqualFold(FieldRate, v))
}

// RateContainsFold applies the ContainsFold predicate on the "rate" field.
func RateContainsFold(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldContainsFold(FieldRate, v))
}

// EffectiveFromEQ applies the EQ predicate on the "effective_from" field.
func EffectiveFromEQ(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveFromNEQ applies the NEQ predicate on the "effective_from" field.
func EffectiveFromNEQ(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNEQ(FieldEffectiveFrom, v))
}

// EffectiveFromIn applies the In predicate on the "effective_from" field.
func EffectiveFromIn(vs ...time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromNotIn applies the NotIn predicate on the "effective_from" field.
func EffectiveFromNotIn(vs ...time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromGT applies the GT predicate on the "effective_from" field.
func EffectiveFromGT(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGT(FieldEffectiveFrom, v))
}

// EffectiveFromGTE applies the GTE predicate on the "effective_from" field.
func EffectiveFromGTE(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGTE(FieldEffectiveFrom, v))
}

// EffectiveFromLT applies the LT predicate on the "effective_from" field.
func EffectiveFromLT(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLT(FieldEffectiveFrom, v))
}

// EffectiveFromLTE applies the LTE predicate on the "effective_from" field.
func EffectiveFromLTE(v time.Time) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLTE(FieldEffectiveFrom, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldHasSuffix(FieldSource, v))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotNull(FieldSource))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldContainsFold(FieldSource, v))
}

// CreatedByUserIDEQ applies the EQ predicate on the "created_by_user_id" field.
func CreatedByUserIDEQ(v int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDNEQ applies the NEQ predicate on the "created_by_user_id" field.
func CreatedByUserIDNEQ(v int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDIn applies the In predicate on the "created_by_user_id" field.
func CreatedByUserIDIn(vs ...int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDNotIn applies the NotIn predicate on the "created_by_user_id" field.
func CreatedByUserIDNotIn(vs ...int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldNotIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDGT applies the GT predicate on the "created_by_user_id" field.
func CreatedByUserIDGT(v int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGT(FieldCreatedByUserID, v))
}

// CreatedByUserIDGTE applies the GTE predicate on the "created_by_user_id" field.
func CreatedByUserIDGTE(v int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldGTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDLT applies the LT predicate on the "created_by_user_id" field.
func CreatedByUserIDLT(v int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLT(FieldCreatedByUserID, v))
}

// CreatedByUserIDLTE applies the LTE predicate on the "created_by_user_id" field.
func CreatedByUserIDLTE(v int64) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.FieldLTE(FieldCreatedByUserID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ValuationFXRate) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ValuationFXRate) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ValuationFXRate) predicate.ValuationFXRate {
	return predicate.ValuationFXRate(sql.NotPredicates(p))
}
