// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcostentry"
)

// AccountCostEntryCreate is the builder for creating a AccountCostEntry entity.
type AccountCostEntryCreate struct {
	config
	mutation *AccountCostEntryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCostEntryCreate) SetCreatedAt(v time.Time) *AccountCostEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillableCreatedAt(v *time.Time) *AccountCostEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountCostEntryCreate) SetUpdatedAt(v time.Time) *AccountCostEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillableUpdatedAt(v *time.Time) *AccountCostEntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountCostEntryCreate) SetAccountID(v int64) *AccountCostEntryCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetPayerUserID sets the "payer_user_id" field.
func (_c *AccountCostEntryCreate) SetPayerUserID(v int64) *AccountCostEntryCreate {
	_c.mutation.SetPayerUserID(v)
	return _c
}

// SetPurchaseSourceID sets the "purchase_source_id" field.
func (_c *AccountCostEntryCreate) SetPurchaseSourceID(v int64) *AccountCostEntryCreate {
	_c.mutation.SetPurchaseSourceID(v)
	return _c
}

// SetNillablePurchaseSourceID sets the "purchase_source_id" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillablePurchaseSourceID(v *int64) *AccountCostEntryCreate {
	if v != nil {
		_c.SetPurchaseSourceID(*v)
	}
	return _c
}

// SetEntryType sets the "entry_type" field.
func (_c *AccountCostEntryCreate) SetEntryType(v string) *AccountCostEntryCreate {
	_c.mutation.SetEntryType(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *AccountCostEntryCreate) SetCurrency(v string) *AccountCostEntryCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillableCurrency(v *string) *AccountCostEntryCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetOriginalAmount sets the "original_amount" field.
func (_c *AccountCostEntryCreate) SetOriginalAmount(v string) *AccountCostEntryCreate {
	_c.mutation.SetOriginalAmount(v)
	return _c
}

// SetCnyAmountMinor sets the "cny_amount_minor" field.
func (_c *AccountCostEntryCreate) SetCnyAmountMinor(v int64) *AccountCostEntryCreate {
	_c.mutation.SetCnyAmountMinor(v)
	return _c
}

// SetFxRate sets the "fx_rate" field.
func (_c *AccountCostEntryCreate) SetFxRate(v string) *AccountCostEntryCreate {
	_c.mutation.SetFxRate(v)
	return _c
}

// SetNillableFxRate sets the "fx_rate" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillableFxRate(v *string) *AccountCostEntryCreate {
	if v != nil {
		_c.SetFxRate(*v)
	}
	return _c
}

// SetServiceStart sets the "service_start" field.
func (_c *AccountCostEntryCreate) SetServiceStart(v time.Time) *AccountCostEntryCreate {
	_c.mutation.SetServiceStart(v)
	return _c
}

// SetServiceEnd sets the "service_end" field.
func (_c *AccountCostEntryCreate) SetServiceEnd(v time.Time) *AccountCostEntryCreate {
	_c.mutation.SetServiceEnd(v)
	return _c
}

// SetWarrantyEnd sets the "warranty_end" field.
func (_c *AccountCostEntryCreate) SetWarrantyEnd(v time.Time) *AccountCostEntryCreate {
	_c.mutation.SetWarrantyEnd(v)
	return _c
}

// SetNillableWarrantyEnd sets the "warranty_end" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillableWarrantyEnd(v *time.Time) *AccountCostEntryCreate {
	if v != nil {
		_c.SetWarrantyEnd(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *AccountCostEntryCreate) SetPaidAt(v time.Time) *AccountCostEntryCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *AccountCostEntryCreate) SetOrderNo(v string) *AccountCostEntryCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillableOrderNo(v *string) *AccountCostEntryCreate {
	if v != nil {
		_c.SetOrderNo(*v)
	}
	return _c
}

// SetPurchaseURL sets the "purchase_url" field.
func (_c *AccountCostEntryCreate) SetPurchaseURL(v string) *AccountCostEntryCreate {
	_c.mutation.SetPurchaseURL(v)
	return _c
}

// SetNillablePurchaseURL sets the "purchase_url" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillablePurchaseURL(v *string) *AccountCostEntryCreate {
	if v != nil {
		_c.SetPurchaseURL(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *AccountCostEntryCreate) SetNote(v string) *AccountCostEntryCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillableNote(v *string) *AccountCostEntryCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetSupersedesID sets the "supersedes_id" field.
func (_c *AccountCostEntryCreate) SetSupersedesID(v int64) *AccountCostEntryCreate {
	_c.mutation.SetSupersedesID(v)
	return _c
}

// SetNillableSupersedesID sets the "supersedes_id" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillableSupersedesID(v *int64) *AccountCostEntryCreate {
	if v != nil {
		_c.SetSupersedesID(*v)
	}
	return _c
}

// SetRelatedAccountID sets the "related_account_id" field.
func (_c *AccountCostEntryCreate) SetRelatedAccountID(v int64) *AccountCostEntryCreate {
	_c.mutation.SetRelatedAccountID(v)
	return _c
}

// SetNillableRelatedAccountID sets the "related_account_id" field if the given value is not nil.
func (_c *AccountCostEntryCreate) SetNillableRelatedAccountID(v *int64) *AccountCostEntryCreate {
	if v != nil {
		_c.SetRelatedAccountID(*v)
	}
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *AccountCostEntryCreate) SetCreatedByUserID(v int64) *AccountCostEntryCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// Mutation returns the AccountCostEntryMutation object of the builder.
func (_c *AccountCostEntryCreate) Mutation() *AccountCostEntryMutation {
	return _c.mutation
}

// Save creates the AccountCostEntry in the database.
func (_c *AccountCostEntryCreate) Save(ctx context.Context) (*AccountCostEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCostEntryCreate) SaveX(ctx context.Context) *AccountCostEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCostEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCostEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCostEntryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountcostentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountcostentry.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := accountcostentry.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.FxRate(); !ok {
		v := accountcostentry.DefaultFxRate
		_c.mutation.SetFxRate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCostEntryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountCostEntry.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountCostEntry.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountCostEntry.account_id"`)}
	}
	if _, ok := _c.mutation.PayerUserID(); !ok {
		return &ValidationError{Name: "payer_user_id", err: errors.New(`ent: missing required field "AccountCostEntry.payer_user_id"`)}
	}
	if _, ok := _c.mutation.EntryType(); !ok {
		return &ValidationError{Name: "entry_type", err: errors.New(`ent: missing required field "AccountCostEntry.entry_type"`)}
	}
	if v, ok := _c.mutation.EntryType(); ok {
		if err := accountcostentry.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.entry_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "AccountCostEntry.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := accountcostentry.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalAmount(); !ok {
		return &ValidationError{Name: "original_amount", err: errors.New(`ent: missing required field "AccountCostEntry.original_amount"`)}
	}
	if v, ok := _c.mutation.OriginalAmount(); ok {
		if err := accountcostentry.OriginalAmountValidator(v); err != nil {
			return &ValidationError{Name: "original_amount", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.original_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CnyAmountMinor(); !ok {
		return &ValidationError{Name: "cny_amount_minor", err: errors.New(`ent: missing required field "AccountCostEntry.cny_amount_minor"`)}
	}
	if _, ok := _c.mutation.FxRate(); !ok {
		return &ValidationError{Name: "fx_rate", err: errors.New(`ent: missing required field "AccountCostEntry.fx_rate"`)}
	}
	if v, ok := _c.mutation.FxRate(); ok {
		if err := accountcostentry.FxRateValidator(v); err != nil {
			return &ValidationError{Name: "fx_rate", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.fx_rate": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServiceStart(); !ok {
		return &ValidationError{Name: "service_start", err: errors.New(`ent: missing required field "AccountCostEntry.service_start"`)}
	}
	if _, ok := _c.mutation.ServiceEnd(); !ok {
		return &ValidationError{Name: "service_end", err: errors.New(`ent: missing required field "AccountCostEntry.service_end"`)}
	}
	if _, ok := _c.mutation.PaidAt(); !ok {
		return &ValidationError{Name: "paid_at", err: errors.New(`ent: missing required field "AccountCostEntry.paid_at"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := accountcostentry.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.order_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PurchaseURL(); ok {
		if err := accountcostentry.PurchaseURLValidator(v); err != nil {
			return &ValidationError{Name: "purchase_url", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.purchase_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedByUserID(); !ok {
		return &ValidationError{Name: "created_by_user_id", err: errors.New(`ent: missing required field "AccountCostEntry.created_by_user_id"`)}
	}
	return nil
}

func (_c *AccountCostEntryCreate) sqlSave(ctx context.Context) (*AccountCostEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCostEntryCreate) createSpec() (*AccountCostEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountCostEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountcostentry.Table, sqlgraph.NewFieldSpec(accountcostentry.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountcostentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountcostentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountcostentry.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.PayerUserID(); ok {
		_spec.SetField(accountcostentry.FieldPayerUserID, field.TypeInt64, value)
		_node.PayerUserID = value
	}
	if value, ok := _c.mutation.PurchaseSourceID(); ok {
		_spec.SetField(accountcostentry.FieldPurchaseSourceID, field.TypeInt64, value)
		_node.PurchaseSourceID = &value
	}
	if value, ok := _c.mutation.EntryType(); ok {
		_spec.SetField(accountcostentry.FieldEntryType, field.TypeString, value)
		_node.EntryType = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(accountcostentry.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.OriginalAmount(); ok {
		_spec.SetField(accountcostentry.FieldOriginalAmount, field.TypeString, value)
		_node.OriginalAmount = value
	}
	if value, ok := _c.mutation.CnyAmountMinor(); ok {
		_spec.SetField(accountcostentry.FieldCnyAmountMinor, field.TypeInt64, value)
		_node.CnyAmountMinor = value
	}
	if value, ok := _c.mutation.FxRate(); ok {
		_spec.SetField(accountcostentry.FieldFxRate, field.TypeString, value)
		_node.FxRate = value
	}
	if value, ok := _c.mutation.ServiceStart(); ok {
		_spec.SetField(accountcostentry.FieldServiceStart, field.TypeTime, value)
		_node.ServiceStart = value
	}
	if value, ok := _c.mutation.ServiceEnd(); ok {
		_spec.SetField(accountcostentry.FieldServiceEnd, field.TypeTime, value)
		_node.ServiceEnd = value
	}
	if value, ok := _c.mutation.WarrantyEnd(); ok {
		_spec.SetField(accountcostentry.FieldWarrantyEnd, field.TypeTime, value)
		_node.WarrantyEnd = &value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(accountcostentry.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(accountcostentry.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = &value
	}
	if value, ok := _c.mutation.PurchaseURL(); ok {
		_spec.SetField(accountcostentry.FieldPurchaseURL, field.TypeString, value)
		_node.PurchaseURL = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(accountcostentry.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.SupersedesID(); ok {
		_spec.SetField(accountcostentry.FieldSupersedesID, field.TypeInt64, value)
		_node.SupersedesID = &value
	}
	if value, ok := _c.mutation.RelatedAccountID(); ok {
		_spec.SetField(accountcostentry.FieldRelatedAccountID, field.TypeInt64, value)
		_node.RelatedAccountID = &value
	}
	if value, ok := _c.mutation.CreatedByUserID(); ok {
		_spec.SetField(accountcostentry.FieldCreatedByUserID, field.TypeInt64, value)
		_node.CreatedByUserID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountCostEntry.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountCostEntryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCostEntryCreate) OnConflict(opts ...sql.ConflictOption) *AccountCostEntryUpsertOne {
	_c.conflict = opts
	return &AccountCostEntryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountCostEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCostEntryCreate) OnConflictColumns(columns ...string) *AccountCostEntryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountCostEntryUpsertOne{
		create: _c,
	}
}

type (
	// AccountCostEntryUpsertOne is the builder for "upsert"-ing
	//  one AccountCostEntry node.
	AccountCostEntryUpsertOne struct {
		create *AccountCostEntryCreate
	}

	// AccountCostEntryUpsert is the "OnConflict" setter.
	AccountCostEntryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountCostEntryUpsert) SetUpdatedAt(v time.Time) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateUpdatedAt() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountCostEntryUpsert) SetAccountID(v int64) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateAccountID() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountCostEntryUpsert) AddAccountID(v int64) *AccountCostEntryUpsert {
	u.Add(accountcostentry.FieldAccountID, v)
	return u
}

// SetPayerUserID sets the "payer_user_id" field.
func (u *AccountCostEntryUpsert) SetPayerUserID(v int64) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldPayerUserID, v)
	return u
}

// UpdatePayerUserID sets the "payer_user_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdatePayerUserID() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldPayerUserID)
	return u
}

// AddPayerUserID adds v to the "payer_user_id" field.
func (u *AccountCostEntryUpsert) AddPayerUserID(v int64) *AccountCostEntryUpsert {
	u.Add(accountcostentry.FieldPayerUserID, v)
	return u
}

// SetPurchaseSourceID sets the "purchase_source_id" field.
func (u *AccountCostEntryUpsert) SetPurchaseSourceID(v int64) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldPurchaseSourceID, v)
	return u
}

// UpdatePurchaseSourceID sets the "purchase_source_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdatePurchaseSourceID() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldPurchaseSourceID)
	return u
}

// AddPurchaseSourceID adds v to the "purchase_source_id" field.
func (u *AccountCostEntryUpsert) AddPurchaseSourceID(v int64) *AccountCostEntryUpsert {
	u.Add(accountcostentry.FieldPurchaseSourceID, v)
	return u
}

// ClearPurchaseSourceID clears the value of the "purchase_source_id" field.
func (u *AccountCostEntryUpsert) ClearPurchaseSourceID() *AccountCostEntryUpsert {
	u.SetNull(accountcostentry.FieldPurchaseSourceID)
	return u
}

// SetEntryType sets the "entry_type" field.
func (u *AccountCostEntryUpsert) SetEntryType(v string) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldEntryType, v)
	return u
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateEntryType() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldEntryType)
	return u
}

// SetCurrency sets the "currency" field.
func (u *AccountCostEntryUpsert) SetCurrency(v string) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateCurrency() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldCurrency)
	return u
}

// SetOriginalAmount sets the "original_amount" field.
func (u *AccountCostEntryUpsert) SetOriginalAmount(v string) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldOriginalAmount, v)
	return u
}

// UpdateOriginalAmount sets the "original_amount" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateOriginalAmount() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldOriginalAmount)
	return u
}

// SetCnyAmountMinor sets the "cny_amount_minor" field.
func (u *AccountCostEntryUpsert) SetCnyAmountMinor(v int64) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldCnyAmountMinor, v)
	return u
}

// UpdateCnyAmountMinor sets the "cny_amount_minor" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateCnyAmountMinor() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldCnyAmountMinor)
	return u
}

// AddCnyAmountMinor adds v to the "cny_amount_minor" field.
func (u *AccountCostEntryUpsert) AddCnyAmountMinor(v int64) *AccountCostEntryUpsert {
	u.Add(accountcostentry.FieldCnyAmountMinor, v)
	return u
}

// SetFxRate sets the "fx_rate" field.
func (u *AccountCostEntryUpsert) SetFxRate(v string) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldFxRate, v)
	return u
}

// UpdateFxRate sets the "fx_rate" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateFxRate() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldFxRate)
	return u
}

// SetServiceStart sets the "service_start" field.
func (u *AccountCostEntryUpsert) SetServiceStart(v time.Time) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldServiceStart, v)
	return u
}

// UpdateServiceStart sets the "service_start" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateServiceStart() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldServiceStart)
	return u
}

// SetServiceEnd sets the "service_end" field.
func (u *AccountCostEntryUpsert) SetServiceEnd(v time.Time) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldServiceEnd, v)
	return u
}

// UpdateServiceEnd sets the "service_end" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateServiceEnd() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldServiceEnd)
	return u
}

// SetWarrantyEnd sets the "warranty_end" field.
func (u *AccountCostEntryUpsert) SetWarrantyEnd(v time.Time) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldWarrantyEnd, v)
	return u
}

// UpdateWarrantyEnd sets the "warranty_end" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateWarrantyEnd() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldWarrantyEnd)
	return u
}

// ClearWarrantyEnd clears the value of the "warranty_end" field.
func (u *AccountCostEntryUpsert) ClearWarrantyEnd() *AccountCostEntryUpsert {
	u.SetNull(accountcostentry.FieldWarrantyEnd)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *AccountCostEntryUpsert) SetPaidAt(v time.Time) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdatePaidAt() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldPaidAt)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *AccountCostEntryUpsert) SetOrderNo(v string) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateOrderNo() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldOrderNo)
	return u
}

// ClearOrderNo clears the value of the "order_no" field.
func (u *AccountCostEntryUpsert) ClearOrderNo() *AccountCostEntryUpsert {
	u.SetNull(accountcostentry.FieldOrderNo)
	return u
}

// SetPurchaseURL sets the "purchase_url" field.
func (u *AccountCostEntryUpsert) SetPurchaseURL(v string) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldPurchaseURL, v)
	return u
}

// UpdatePurchaseURL sets the "purchase_url" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdatePurchaseURL() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldPurchaseURL)
	return u
}

// ClearPurchaseURL clears the value of the "purchase_url" field.
func (u *AccountCostEntryUpsert) ClearPurchaseURL() *AccountCostEntryUpsert {
	u.SetNull(accountcostentry.FieldPurchaseURL)
	return u
}

// SetNote sets the "note" field.
func (u *AccountCostEntryUpsert) SetNote(v string) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateNote() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *AccountCostEntryUpsert) ClearNote() *AccountCostEntryUpsert {
	u.SetNull(accountcostentry.FieldNote)
	return u
}

// SetSupersedesID sets the "supersedes_id" field.
func (u *AccountCostEntryUpsert) SetSupersedesID(v int64) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldSupersedesID, v)
	return u
}

// UpdateSupersedesID sets the "supersedes_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateSupersedesID() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldSupersedesID)
	return u
}

// AddSupersedesID adds v to the "supersedes_id" field.
func (u *AccountCostEntryUpsert) AddSupersedesID(v int64) *AccountCostEntryUpsert {
	u.Add(accountcostentry.FieldSupersedesID, v)
	return u
}

// ClearSupersedesID clears the value of the "supersedes_id" field.
func (u *AccountCostEntryUpsert) ClearSupersedesID() *AccountCostEntryUpsert {
	u.SetNull(accountcostentry.FieldSupersedesID)
	return u
}

// SetRelatedAccountID sets the "related_account_id" field.
func (u *AccountCostEntryUpsert) SetRelatedAccountID(v int64) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldRelatedAccountID, v)
	return u
}

// UpdateRelatedAccountID sets the "related_account_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateRelatedAccountID() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldRelatedAccountID)
	return u
}

// AddRelatedAccountID adds v to the "related_account_id" field.
func (u *AccountCostEntryUpsert) AddRelatedAccountID(v int64) *AccountCostEntryUpsert {
	u.Add(accountcostentry.FieldRelatedAccountID, v)
	return u
}

// ClearRelatedAccountID clears the value of the "related_account_id" field.
func (u *AccountCostEntryUpsert) ClearRelatedAccountID() *AccountCostEntryUpsert {
	u.SetNull(accountcostentry.FieldRelatedAccountID)
	return u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *AccountCostEntryUpsert) SetCreatedByUserID(v int64) *AccountCostEntryUpsert {
	u.Set(accountcostentry.FieldCreatedByUserID, v)
	return u
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsert) UpdateCreatedByUserID() *AccountCostEntryUpsert {
	u.SetExcluded(accountcostentry.FieldCreatedByUserID)
	return u
}

// AddCreatedByUserID adds v to the "created_by_user_id" field.
func (u *AccountCostEntryUpsert) AddCreatedByUserID(v int64) *AccountCostEntryUpsert {
	u.Add(accountcostentry.FieldCreatedByUserID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountCostEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountCostEntryUpsertOne) UpdateNewValues() *AccountCostEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountcostentry.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountCostEntry.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountCostEntryUpsertOne) Ignore() *AccountCostEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountCostEntryUpsertOne) DoNothing() *AccountCostEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCostEntryCreate.OnConflict
// documentation for more info.
func (u *AccountCostEntryUpsertOne) Update(set func(*AccountCostEntryUpsert)) *AccountCostEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountCostEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountCostEntryUpsertOne) SetUpdatedAt(v time.Time) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateUpdatedAt() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountCostEntryUpsertOne) SetAccountID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountCostEntryUpsertOne) AddAccountID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateAccountID() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateAccountID()
	})
}

// SetPayerUserID sets the "payer_user_id" field.
func (u *AccountCostEntryUpsertOne) SetPayerUserID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetPayerUserID(v)
	})
}

// AddPayerUserID adds v to the "payer_user_id" field.
func (u *AccountCostEntryUpsertOne) AddPayerUserID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddPayerUserID(v)
	})
}

// UpdatePayerUserID sets the "payer_user_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdatePayerUserID() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdatePayerUserID()
	})
}

// SetPurchaseSourceID sets the "purchase_source_id" field.
func (u *AccountCostEntryUpsertOne) SetPurchaseSourceID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetPurchaseSourceID(v)
	})
}

// AddPurchaseSourceID adds v to the "purchase_source_id" field.
func (u *AccountCostEntryUpsertOne) AddPurchaseSourceID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddPurchaseSourceID(v)
	})
}

// UpdatePurchaseSourceID sets the "purchase_source_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdatePurchaseSourceID() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdatePurchaseSourceID()
	})
}

// ClearPurchaseSourceID clears the value of the "purchase_source_id" field.
func (u *AccountCostEntryUpsertOne) ClearPurchaseSourceID() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearPurchaseSourceID()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *AccountCostEntryUpsertOne) SetEntryType(v string) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateEntryType() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateEntryType()
	})
}

// SetCurrency sets the "currency" field.
func (u *AccountCostEntryUpsertOne) SetCurrency(v string) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateCurrency() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateCurrency()
	})
}

// SetOriginalAmount sets the "original_amount" field.
func (u *AccountCostEntryUpsertOne) SetOriginalAmount(v string) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetOriginalAmount(v)
	})
}

// UpdateOriginalAmount sets the "original_amount" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateOriginalAmount() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateOriginalAmount()
	})
}

// SetCnyAmountMinor sets the "cny_amount_minor" field.
func (u *AccountCostEntryUpsertOne) SetCnyAmountMinor(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetCnyAmountMinor(v)
	})
}

// AddCnyAmountMinor adds v to the "cny_amount_minor" field.
func (u *AccountCostEntryUpsertOne) AddCnyAmountMinor(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddCnyAmountMinor(v)
	})
}

// UpdateCnyAmountMinor sets the "cny_amount_minor" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateCnyAmountMinor() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateCnyAmountMinor()
	})
}

// SetFxRate sets the "fx_rate" field.
func (u *AccountCostEntryUpsertOne) SetFxRate(v string) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetFxRate(v)
	})
}

// UpdateFxRate sets the "fx_rate" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateFxRate() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateFxRate()
	})
}

// SetServiceStart sets the "service_start" field.
func (u *AccountCostEntryUpsertOne) SetServiceStart(v time.Time) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetServiceStart(v)
	})
}

// UpdateServiceStart sets the "service_start" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateServiceStart() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateServiceStart()
	})
}

// SetServiceEnd sets the "service_end" field.
func (u *AccountCostEntryUpsertOne) SetServiceEnd(v time.Time) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetServiceEnd(v)
	})
}

// UpdateServiceEnd sets the "service_end" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateServiceEnd() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateServiceEnd()
	})
}

// SetWarrantyEnd sets the "warranty_end" field.
func (u *AccountCostEntryUpsertOne) SetWarrantyEnd(v time.Time) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetWarrantyEnd(v)
	})
}

// UpdateWarrantyEnd sets the "warranty_end" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateWarrantyEnd() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateWarrantyEnd()
	})
}

// ClearWarrantyEnd clears the value of the "warranty_end" field.
func (u *AccountCostEntryUpsertOne) ClearWarrantyEnd() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearWarrantyEnd()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *AccountCostEntryUpsertOne) SetPaidAt(v time.Time) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdatePaidAt() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdatePaidAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *AccountCostEntryUpsertOne) SetOrderNo(v string) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateOrderNo() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateOrderNo()
	})
}

// ClearOrderNo clears the value of the "order_no" field.
func (u *AccountCostEntryUpsertOne) ClearOrderNo() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearOrderNo()
	})
}

// SetPurchaseURL sets the "purchase_url" field.
func (u *AccountCostEntryUpsertOne) SetPurchaseURL(v string) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetPurchaseURL(v)
	})
}

// UpdatePurchaseURL sets the "purchase_url" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdatePurchaseURL() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdatePurchaseURL()
	})
}

// ClearPurchaseURL clears the value of the "purchase_url" field.
func (u *AccountCostEntryUpsertOne) ClearPurchaseURL() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearPurchaseURL()
	})
}

// SetNote sets the "note" field.
func (u *AccountCostEntryUpsertOne) SetNote(v string) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateNote() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *AccountCostEntryUpsertOne) ClearNote() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearNote()
	})
}

// SetSupersedesID sets the "supersedes_id" field.
func (u *AccountCostEntryUpsertOne) SetSupersedesID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetSupersedesID(v)
	})
}

// AddSupersedesID adds v to the "supersedes_id" field.
func (u *AccountCostEntryUpsertOne) AddSupersedesID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddSupersedesID(v)
	})
}

// UpdateSupersedesID sets the "supersedes_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateSupersedesID() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateSupersedesID()
	})
}

// ClearSupersedesID clears the value of the "supersedes_id" field.
func (u *AccountCostEntryUpsertOne) ClearSupersedesID() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearSupersedesID()
	})
}

// SetRelatedAccountID sets the "related_account_id" field.
func (u *AccountCostEntryUpsertOne) SetRelatedAccountID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetRelatedAccountID(v)
	})
}

// AddRelatedAccountID adds v to the "related_account_id" field.
func (u *AccountCostEntryUpsertOne) AddRelatedAccountID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddRelatedAccountID(v)
	})
}

// UpdateRelatedAccountID sets the "related_account_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateRelatedAccountID() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateRelatedAccountID()
	})
}

// ClearRelatedAccountID clears the value of the "related_account_id" field.
func (u *AccountCostEntryUpsertOne) ClearRelatedAccountID() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearRelatedAccountID()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *AccountCostEntryUpsertOne) SetCreatedByUserID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// AddCreatedByUserID adds v to the "created_by_user_id" field.
func (u *AccountCostEntryUpsertOne) AddCreatedByUserID(v int64) *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertOne) UpdateCreatedByUserID() *AccountCostEntryUpsertOne {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// Exec executes the query.
func (u *AccountCostEntryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCostEntryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountCostEntryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountCostEntryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountCostEntryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountCostEntryCreateBulk is the builder for creating many AccountCostEntry entities in bulk.
type AccountCostEntryCreateBulk struct {
	config
	err      error
	builders []*AccountCostEntryCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountCostEntry entities in the database.
func (_c *AccountCostEntryCreateBulk) Save(ctx context.Context) ([]*AccountCostEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountCostEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountCostEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCostEntryCreateBulk) SaveX(ctx context.Context) []*AccountCostEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCostEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCostEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountCostEntry.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountCostEntryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCostEntryCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountCostEntryUpsertBulk {
	_c.conflict = opts
	return &AccountCostEntryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountCostEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCostEntryCreateBulk) OnConflictColumns(columns ...string) *AccountCostEntryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountCostEntryUpsertBulk{
		create: _c,
	}
}

// AccountCostEntryUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountCostEntry nodes.
type AccountCostEntryUpsertBulk struct {
	create *AccountCostEntryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountCostEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountCostEntryUpsertBulk) UpdateNewValues() *AccountCostEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountcostentry.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountCostEntry.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountCostEntryUpsertBulk) Ignore() *AccountCostEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountCostEntryUpsertBulk) DoNothing() *AccountCostEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCostEntryCreateBulk.OnConflict
// documentation for more info.
func (u *AccountCostEntryUpsertBulk) Update(set func(*AccountCostEntryUpsert)) *AccountCostEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountCostEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountCostEntryUpsertBulk) SetUpdatedAt(v time.Time) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateUpdatedAt() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountCostEntryUpsertBulk) SetAccountID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountCostEntryUpsertBulk) AddAccountID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateAccountID() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateAccountID()
	})
}

// SetPayerUserID sets the "payer_user_id" field.
func (u *AccountCostEntryUpsertBulk) SetPayerUserID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetPayerUserID(v)
	})
}

// AddPayerUserID adds v to the "payer_user_id" field.
func (u *AccountCostEntryUpsertBulk) AddPayerUserID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddPayerUserID(v)
	})
}

// UpdatePayerUserID sets the "payer_user_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdatePayerUserID() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdatePayerUserID()
	})
}

// SetPurchaseSourceID sets the "purchase_source_id" field.
func (u *AccountCostEntryUpsertBulk) SetPurchaseSourceID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetPurchaseSourceID(v)
	})
}

// AddPurchaseSourceID adds v to the "purchase_source_id" field.
func (u *AccountCostEntryUpsertBulk) AddPurchaseSourceID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddPurchaseSourceID(v)
	})
}

// UpdatePurchaseSourceID sets the "purchase_source_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdatePurchaseSourceID() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdatePurchaseSourceID()
	})
}

// ClearPurchaseSourceID clears the value of the "purchase_source_id" field.
func (u *AccountCostEntryUpsertBulk) ClearPurchaseSourceID() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearPurchaseSourceID()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *AccountCostEntryUpsertBulk) SetEntryType(v string) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateEntryType() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateEntryType()
	})
}

// SetCurrency sets the "currency" field.
func (u *AccountCostEntryUpsertBulk) SetCurrency(v string) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateCurrency() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateCurrency()
	})
}

// SetOriginalAmount sets the "original_amount" field.
func (u *AccountCostEntryUpsertBulk) SetOriginalAmount(v string) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetOriginalAmount(v)
	})
}

// UpdateOriginalAmount sets the "original_amount" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateOriginalAmount() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateOriginalAmount()
	})
}

// SetCnyAmountMinor sets the "cny_amount_minor" field.
func (u *AccountCostEntryUpsertBulk) SetCnyAmountMinor(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetCnyAmountMinor(v)
	})
}

// AddCnyAmountMinor adds v to the "cny_amount_minor" field.
func (u *AccountCostEntryUpsertBulk) AddCnyAmountMinor(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddCnyAmountMinor(v)
	})
}

// UpdateCnyAmountMinor sets the "cny_amount_minor" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateCnyAmountMinor() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateCnyAmountMinor()
	})
}

// SetFxRate sets the "fx_rate" field.
func (u *AccountCostEntryUpsertBulk) SetFxRate(v string) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetFxRate(v)
	})
}

// UpdateFxRate sets the "fx_rate" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateFxRate() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateFxRate()
	})
}

// SetServiceStart sets the "service_start" field.
func (u *AccountCostEntryUpsertBulk) SetServiceStart(v time.Time) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetServiceStart(v)
	})
}

// UpdateServiceStart sets the "service_start" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateServiceStart() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateServiceStart()
	})
}

// SetServiceEnd sets the "service_end" field.
func (u *AccountCostEntryUpsertBulk) SetServiceEnd(v time.Time) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetServiceEnd(v)
	})
}

// UpdateServiceEnd sets the "service_end" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateServiceEnd() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateServiceEnd()
	})
}

// SetWarrantyEnd sets the "warranty_end" field.
func (u *AccountCostEntryUpsertBulk) SetWarrantyEnd(v time.Time) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetWarrantyEnd(v)
	})
}

// UpdateWarrantyEnd sets the "warranty_end" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateWarrantyEnd() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateWarrantyEnd()
	})
}

// ClearWarrantyEnd clears the value of the "warranty_end" field.
func (u *AccountCostEntryUpsertBulk) ClearWarrantyEnd() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearWarrantyEnd()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *AccountCostEntryUpsertBulk) SetPaidAt(v time.Time) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdatePaidAt() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdatePaidAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *AccountCostEntryUpsertBulk) SetOrderNo(v string) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateOrderNo() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateOrderNo()
	})
}

// ClearOrderNo clears the value of the "order_no" field.
func (u *AccountCostEntryUpsertBulk) ClearOrderNo() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearOrderNo()
	})
}

// SetPurchaseURL sets the "purchase_url" field.
func (u *AccountCostEntryUpsertBulk) SetPurchaseURL(v string) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetPurchaseURL(v)
	})
}

// UpdatePurchaseURL sets the "purchase_url" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdatePurchaseURL() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdatePurchaseURL()
	})
}

// ClearPurchaseURL clears the value of the "purchase_url" field.
func (u *AccountCostEntryUpsertBulk) ClearPurchaseURL() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearPurchaseURL()
	})
}

// SetNote sets the "note" field.
func (u *AccountCostEntryUpsertBulk) SetNote(v string) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateNote() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *AccountCostEntryUpsertBulk) ClearNote() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearNote()
	})
}

// SetSupersedesID sets the "supersedes_id" field.
func (u *AccountCostEntryUpsertBulk) SetSupersedesID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetSupersedesID(v)
	})
}

// AddSupersedesID adds v to the "supersedes_id" field.
func (u *AccountCostEntryUpsertBulk) AddSupersedesID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddSupersedesID(v)
	})
}

// UpdateSupersedesID sets the "supersedes_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateSupersedesID() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateSupersedesID()
	})
}

// ClearSupersedesID clears the value of the "supersedes_id" field.
func (u *AccountCostEntryUpsertBulk) ClearSupersedesID() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearSupersedesID()
	})
}

// SetRelatedAccountID sets the "related_account_id" field.
func (u *AccountCostEntryUpsertBulk) SetRelatedAccountID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetRelatedAccountID(v)
	})
}

// AddRelatedAccountID adds v to the "related_account_id" field.
func (u *AccountCostEntryUpsertBulk) AddRelatedAccountID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddRelatedAccountID(v)
	})
}

// UpdateRelatedAccountID sets the "related_account_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateRelatedAccountID() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateRelatedAccountID()
	})
}

// ClearRelatedAccountID clears the value of the "related_account_id" field.
func (u *AccountCostEntryUpsertBulk) ClearRelatedAccountID() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.ClearRelatedAccountID()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *AccountCostEntryUpsertBulk) SetCreatedByUserID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// AddCreatedByUserID adds v to the "created_by_user_id" field.
func (u *AccountCostEntryUpsertBulk) AddCreatedByUserID(v int64) *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.AddCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *AccountCostEntryUpsertBulk) UpdateCreatedByUserID() *AccountCostEntryUpsertBulk {
	return u.Update(func(s *AccountCostEntryUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// Exec executes the query.
func (u *AccountCostEntryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountCostEntryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCostEntryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountCostEntryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
