// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountlifecycleevent"
)

// AccountLifecycleEventCreate is the builder for creating a AccountLifecycleEvent entity.
type AccountLifecycleEventCreate struct {
	config
	mutation *AccountLifecycleEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountLifecycleEventCreate) SetCreatedAt(v time.Time) *AccountLifecycleEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountLifecycleEventCreate) SetNillableCreatedAt(v *time.Time) *AccountLifecycleEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountLifecycleEventCreate) SetUpdatedAt(v time.Time) *AccountLifecycleEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountLifecycleEventCreate) SetNillableUpdatedAt(v *time.Time) *AccountLifecycleEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountLifecycleEventCreate) SetAccountID(v int64) *AccountLifecycleEventCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *AccountLifecycleEventCreate) SetEventType(v string) *AccountLifecycleEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *AccountLifecycleEventCreate) SetOccurredAt(v time.Time) *AccountLifecycleEventCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *AccountLifecycleEventCreate) SetReason(v string) *AccountLifecycleEventCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *AccountLifecycleEventCreate) SetNillableReason(v *string) *AccountLifecycleEventCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetReplacementAccountID sets the "replacement_account_id" field.
func (_c *AccountLifecycleEventCreate) SetReplacementAccountID(v int64) *AccountLifecycleEventCreate {
	_c.mutation.SetReplacementAccountID(v)
	return _c
}

// SetNillableReplacementAccountID sets the "replacement_account_id" field if the given value is not nil.
func (_c *AccountLifecycleEventCreate) SetNillableReplacementAccountID(v *int64) *AccountLifecycleEventCreate {
	if v != nil {
		_c.SetReplacementAccountID(*v)
	}
	return _c
}

// SetTransferredCostMinor sets the "transferred_cost_minor" field.
func (_c *AccountLifecycleEventCreate) SetTransferredCostMinor(v int64) *AccountLifecycleEventCreate {
	_c.mutation.SetTransferredCostMinor(v)
	return _c
}

// SetNillableTransferredCostMinor sets the "transferred_cost_minor" field if the given value is not nil.
func (_c *AccountLifecycleEventCreate) SetNillableTransferredCostMinor(v *int64) *AccountLifecycleEventCreate {
	if v != nil {
		_c.SetTransferredCostMinor(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *AccountLifecycleEventCreate) SetSource(v string) *AccountLifecycleEventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *AccountLifecycleEventCreate) SetNillableSource(v *string) *AccountLifecycleEventCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_c *AccountLifecycleEventCreate) SetCreatedByUserID(v int64) *AccountLifecycleEventCreate {
	_c.mutation.SetCreatedByUserID(v)
	return _c
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_c *AccountLifecycleEventCreate) SetNillableCreatedByUserID(v *int64) *AccountLifecycleEventCreate {
	if v != nil {
		_c.SetCreatedByUserID(*v)
	}
	return _c
}

// Mutation returns the AccountLifecycleEventMutation object of the builder.
func (_c *AccountLifecycleEventCreate) Mutation() *AccountLifecycleEventMutation {
	return _c.mutation
}

// Save creates the AccountLifecycleEvent in the database.
func (_c *AccountLifecycleEventCreate) Save(ctx context.Context) (*AccountLifecycleEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountLifecycleEventCreate) SaveX(ctx context.Context) *AccountLifecycleEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountLifecycleEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountLifecycleEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountLifecycleEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountlifecycleevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountlifecycleevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TransferredCostMinor(); !ok {
		v := accountlifecycleevent.DefaultTransferredCostMinor
		_c.mutation.SetTransferredCostMinor(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := accountlifecycleevent.DefaultSource
		_c.mutation.SetSource(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountLifecycleEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountLifecycleEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountLifecycleEvent.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountLifecycleEvent.account_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "AccountLifecycleEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := accountlifecycleevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AccountLifecycleEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "AccountLifecycleEvent.occurred_at"`)}
	}
	if _, ok := _c.mutation.TransferredCostMinor(); !ok {
		return &ValidationError{Name: "transferred_cost_minor", err: errors.New(`ent: missing required field "AccountLifecycleEvent.transferred_cost_minor"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "AccountLifecycleEvent.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := accountlifecycleevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AccountLifecycleEvent.source": %w`, err)}
		}
	}
	return nil
}

func (_c *AccountLifecycleEventCreate) sqlSave(ctx context.Context) (*AccountLifecycleEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountLifecycleEventCreate) createSpec() (*AccountLifecycleEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountLifecycleEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountlifecycleevent.Table, sqlgraph.NewFieldSpec(accountlifecycleevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountlifecycleevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountlifecycleevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountlifecycleevent.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(accountlifecycleevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(accountlifecycleevent.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(accountlifecycleevent.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.ReplacementAccountID(); ok {
		_spec.SetField(accountlifecycleevent.FieldReplacementAccountID, field.TypeInt64, value)
		_node.ReplacementAccountID = &value
	}
	if value, ok := _c.mutation.TransferredCostMinor(); ok {
		_spec.SetField(accountlifecycleevent.FieldTransferredCostMinor, field.TypeInt64, value)
		_node.TransferredCostMinor = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(accountlifecycleevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.CreatedByUserID(); ok {
		_spec.SetField(accountlifecycleevent.FieldCreatedByUserID, field.TypeInt64, value)
		_node.CreatedByUserID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountLifecycleEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountLifecycleEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountLifecycleEventCreate) OnConflict(opts ...sql.ConflictOption) *AccountLifecycleEventUpsertOne {
	_c.conflict = opts
	return &AccountLifecycleEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountLifecycleEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountLifecycleEventCreate) OnConflictColumns(columns ...string) *AccountLifecycleEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountLifecycleEventUpsertOne{
		create: _c,
	}
}

type (
	// AccountLifecycleEventUpsertOne is the builder for "upsert"-ing
	//  one AccountLifecycleEvent node.
	AccountLifecycleEventUpsertOne struct {
		create *AccountLifecycleEventCreate
	}

	// AccountLifecycleEventUpsert is the "OnConflict" setter.
	AccountLifecycleEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountLifecycleEventUpsert) SetUpdatedAt(v time.Time) *AccountLifecycleEventUpsert {
	u.Set(accountlifecycleevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsert) UpdateUpdatedAt() *AccountLifecycleEventUpsert {
	u.SetExcluded(accountlifecycleevent.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountLifecycleEventUpsert) SetAccountID(v int64) *AccountLifecycleEventUpsert {
	u.Set(accountlifecycleevent.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsert) UpdateAccountID() *AccountLifecycleEventUpsert {
	u.SetExcluded(accountlifecycleevent.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountLifecycleEventUpsert) AddAccountID(v int64) *AccountLifecycleEventUpsert {
	u.Add(accountlifecycleevent.FieldAccountID, v)
	return u
}

// SetEventType sets the "event_type" field.
func (u *AccountLifecycleEventUpsert) SetEventType(v string) *AccountLifecycleEventUpsert {
	u.Set(accountlifecycleevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsert) UpdateEventType() *AccountLifecycleEventUpsert {
	u.SetExcluded(accountlifecycleevent.FieldEventType)
	return u
}

// SetOccurredAt sets the "occurred_at" field.
func (u *AccountLifecycleEventUpsert) SetOccurredAt(v time.Time) *AccountLifecycleEventUpsert {
	u.Set(accountlifecycleevent.FieldOccurredAt, v)
	return u
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsert) UpdateOccurredAt() *AccountLifecycleEventUpsert {
	u.SetExcluded(accountlifecycleevent.FieldOccurredAt)
	return u
}

// SetReason sets the "reason" field.
func (u *AccountLifecycleEventUpsert) SetReason(v string) *AccountLifecycleEventUpsert {
	u.Set(accountlifecycleevent.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsert) UpdateReason() *AccountLifecycleEventUpsert {
	u.SetExcluded(accountlifecycleevent.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *AccountLifecycleEventUpsert) ClearReason() *AccountLifecycleEventUpsert {
	u.SetNull(accountlifecycleevent.FieldReason)
	return u
}

// SetReplacementAccountID sets the "replacement_account_id" field.
func (u *AccountLifecycleEventUpsert) SetReplacementAccountID(v int64) *AccountLifecycleEventUpsert {
	u.Set(accountlifecycleevent.FieldReplacementAccountID, v)
	return u
}

// UpdateReplacementAccountID sets the "replacement_account_id" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsert) UpdateReplacementAccountID() *AccountLifecycleEventUpsert {
	u.SetExcluded(accountlifecycleevent.FieldReplacementAccountID)
	return u
}

// AddReplacementAccountID adds v to the "replacement_account_id" field.
func (u *AccountLifecycleEventUpsert) AddReplacementAccountID(v int64) *AccountLifecycleEventUpsert {
	u.Add(accountlifecycleevent.FieldReplacementAccountID, v)
	return u
}

// ClearReplacementAccountID clears the value of the "replacement_account_id" field.
func (u *AccountLifecycleEventUpsert) ClearReplacementAccountID() *AccountLifecycleEventUpsert {
	u.SetNull(accountlifecycleevent.FieldReplacementAccountID)
	return u
}

// SetTransferredCostMinor sets the "transferred_cost_minor" field.
func (u *AccountLifecycleEventUpsert) SetTransferredCostMinor(v int64) *AccountLifecycleEventUpsert {
	u.Set(accountlifecycleevent.FieldTransferredCostMinor, v)
	return u
}

// UpdateTransferredCostMinor sets the "transferred_cost_minor" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsert) UpdateTransferredCostMinor() *AccountLifecycleEventUpsert {
	u.SetExcluded(accountlifecycleevent.FieldTransferredCostMinor)
	return u
}

// AddTransferredCostMinor adds v to the "transferred_cost_minor" field.
func (u *AccountLifecycleEventUpsert) AddTransferredCostMinor(v int64) *AccountLifecycleEventUpsert {
	u.Add(accountlifecycleevent.FieldTransferredCostMinor, v)
	return u
}

// SetSource sets the "source" field.
func (u *AccountLifecycleEventUpsert) SetSource(v string) *AccountLifecycleEventUpsert {
	u.Set(accountlifecycleevent.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsert) UpdateSource() *AccountLifecycleEventUpsert {
	u.SetExcluded(accountlifecycleevent.FieldSource)
	return u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *AccountLifecycleEventUpsert) SetCreatedByUserID(v int64) *AccountLifecycleEventUpsert {
	u.Set(accountlifecycleevent.FieldCreatedByUserID, v)
	return u
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsert) UpdateCreatedByUserID() *AccountLifecycleEventUpsert {
	u.SetExcluded(accountlifecycleevent.FieldCreatedByUserID)
	return u
}

// AddCreatedByUserID adds v to the "created_by_user_id" field.
func (u *AccountLifecycleEventUpsert) AddCreatedByUserID(v int64) *AccountLifecycleEventUpsert {
	u.Add(accountlifecycleevent.FieldCreatedByUserID, v)
	return u
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (u *AccountLifecycleEventUpsert) ClearCreatedByUserID() *AccountLifecycleEventUpsert {
	u.SetNull(accountlifecycleevent.FieldCreatedByUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountLifecycleEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountLifecycleEventUpsertOne) UpdateNewValues() *AccountLifecycleEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountlifecycleevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountLifecycleEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountLifecycleEventUpsertOne) Ignore() *AccountLifecycleEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountLifecycleEventUpsertOne) DoNothing() *AccountLifecycleEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountLifecycleEventCreate.OnConflict
// documentation for more info.
func (u *AccountLifecycleEventUpsertOne) Update(set func(*AccountLifecycleEventUpsert)) *AccountLifecycleEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountLifecycleEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountLifecycleEventUpsertOne) SetUpdatedAt(v time.Time) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertOne) UpdateUpdatedAt() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountLifecycleEventUpsertOne) SetAccountID(v int64) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountLifecycleEventUpsertOne) AddAccountID(v int64) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertOne) UpdateAccountID() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateAccountID()
	})
}

// SetEventType sets the "event_type" field.
func (u *AccountLifecycleEventUpsertOne) SetEventType(v string) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertOne) UpdateEventType() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateEventType()
	})
}

// SetOccurredAt sets the "occurred_at" field.
func (u *AccountLifecycleEventUpsertOne) SetOccurredAt(v time.Time) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetOccurredAt(v)
	})
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertOne) UpdateOccurredAt() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateOccurredAt()
	})
}

// SetReason sets the "reason" field.
func (u *AccountLifecycleEventUpsertOne) SetReason(v string) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertOne) UpdateReason() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *AccountLifecycleEventUpsertOne) ClearReason() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.ClearReason()
	})
}

// SetReplacementAccountID sets the "replacement_account_id" field.
func (u *AccountLifecycleEventUpsertOne) SetReplacementAccountID(v int64) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetReplacementAccountID(v)
	})
}

// AddReplacementAccountID adds v to the "replacement_account_id" field.
func (u *AccountLifecycleEventUpsertOne) AddReplacementAccountID(v int64) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.AddReplacementAccountID(v)
	})
}

// UpdateReplacementAccountID sets the "replacement_account_id" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertOne) UpdateReplacementAccountID() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateReplacementAccountID()
	})
}

// ClearReplacementAccountID clears the value of the "replacement_account_id" field.
func (u *AccountLifecycleEventUpsertOne) ClearReplacementAccountID() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.ClearReplacementAccountID()
	})
}

// SetTransferredCostMinor sets the "transferred_cost_minor" field.
func (u *AccountLifecycleEventUpsertOne) SetTransferredCostMinor(v int64) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetTransferredCostMinor(v)
	})
}

// AddTransferredCostMinor adds v to the "transferred_cost_minor" field.
func (u *AccountLifecycleEventUpsertOne) AddTransferredCostMinor(v int64) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.AddTransferredCostMinor(v)
	})
}

// UpdateTransferredCostMinor sets the "transferred_cost_minor" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertOne) UpdateTransferredCostMinor() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateTransferredCostMinor()
	})
}

// SetSource sets the "source" field.
func (u *AccountLifecycleEventUpsertOne) SetSource(v string) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertOne) UpdateSource() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateSource()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *AccountLifecycleEventUpsertOne) SetCreatedByUserID(v int64) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// AddCreatedByUserID adds v to the "created_by_user_id" field.
func (u *AccountLifecycleEventUpsertOne) AddCreatedByUserID(v int64) *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.AddCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertOne) UpdateCreatedByUserID() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (u *AccountLifecycleEventUpsertOne) ClearCreatedByUserID() *AccountLifecycleEventUpsertOne {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.ClearCreatedByUserID()
	})
}

// Exec executes the query.
func (u *AccountLifecycleEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountLifecycleEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountLifecycleEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountLifecycleEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountLifecycleEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountLifecycleEventCreateBulk is the builder for creating many AccountLifecycleEvent entities in bulk.
type AccountLifecycleEventCreateBulk struct {
	config
	err      error
	builders []*AccountLifecycleEventCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountLifecycleEvent entities in the database.
func (_c *AccountLifecycleEventCreateBulk) Save(ctx context.Context) ([]*AccountLifecycleEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountLifecycleEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountLifecycleEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountLifecycleEventCreateBulk) SaveX(ctx context.Context) []*AccountLifecycleEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountLifecycleEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountLifecycleEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountLifecycleEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountLifecycleEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountLifecycleEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountLifecycleEventUpsertBulk {
	_c.conflict = opts
	return &AccountLifecycleEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountLifecycleEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountLifecycleEventCreateBulk) OnConflictColumns(columns ...string) *AccountLifecycleEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountLifecycleEventUpsertBulk{
		create: _c,
	}
}

// AccountLifecycleEventUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountLifecycleEvent nodes.
type AccountLifecycleEventUpsertBulk struct {
	create *AccountLifecycleEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountLifecycleEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountLifecycleEventUpsertBulk) UpdateNewValues() *AccountLifecycleEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountlifecycleevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountLifecycleEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountLifecycleEventUpsertBulk) Ignore() *AccountLifecycleEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountLifecycleEventUpsertBulk) DoNothing() *AccountLifecycleEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountLifecycleEventCreateBulk.OnConflict
// documentation for more info.
func (u *AccountLifecycleEventUpsertBulk) Update(set func(*AccountLifecycleEventUpsert)) *AccountLifecycleEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountLifecycleEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountLifecycleEventUpsertBulk) SetUpdatedAt(v time.Time) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertBulk) UpdateUpdatedAt() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountLifecycleEventUpsertBulk) SetAccountID(v int64) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountLifecycleEventUpsertBulk) AddAccountID(v int64) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertBulk) UpdateAccountID() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateAccountID()
	})
}

// SetEventType sets the "event_type" field.
func (u *AccountLifecycleEventUpsertBulk) SetEventType(v string) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertBulk) UpdateEventType() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateEventType()
	})
}

// SetOccurredAt sets the "occurred_at" field.
func (u *AccountLifecycleEventUpsertBulk) SetOccurredAt(v time.Time) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetOccurredAt(v)
	})
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertBulk) UpdateOccurredAt() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateOccurredAt()
	})
}

// SetReason sets the "reason" field.
func (u *AccountLifecycleEventUpsertBulk) SetReason(v string) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertBulk) UpdateReason() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *AccountLifecycleEventUpsertBulk) ClearReason() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.ClearReason()
	})
}

// SetReplacementAccountID sets the "replacement_account_id" field.
func (u *AccountLifecycleEventUpsertBulk) SetReplacementAccountID(v int64) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetReplacementAccountID(v)
	})
}

// AddReplacementAccountID adds v to the "replacement_account_id" field.
func (u *AccountLifecycleEventUpsertBulk) AddReplacementAccountID(v int64) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.AddReplacementAccountID(v)
	})
}

// UpdateReplacementAccountID sets the "replacement_account_id" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertBulk) UpdateReplacementAccountID() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateReplacementAccountID()
	})
}

// ClearReplacementAccountID clears the value of the "replacement_account_id" field.
func (u *AccountLifecycleEventUpsertBulk) ClearReplacementAccountID() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.ClearReplacementAccountID()
	})
}

// SetTransferredCostMinor sets the "transferred_cost_minor" field.
func (u *AccountLifecycleEventUpsertBulk) SetTransferredCostMinor(v int64) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetTransferredCostMinor(v)
	})
}

// AddTransferredCostMinor adds v to the "transferred_cost_minor" field.
func (u *AccountLifecycleEventUpsertBulk) AddTransferredCostMinor(v int64) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.AddTransferredCostMinor(v)
	})
}

// UpdateTransferredCostMinor sets the "transferred_cost_minor" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertBulk) UpdateTransferredCostMinor() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateTransferredCostMinor()
	})
}

// SetSource sets the "source" field.
func (u *AccountLifecycleEventUpsertBulk) SetSource(v string) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertBulk) UpdateSource() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateSource()
	})
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (u *AccountLifecycleEventUpsertBulk) SetCreatedByUserID(v int64) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.SetCreatedByUserID(v)
	})
}

// AddCreatedByUserID adds v to the "created_by_user_id" field.
func (u *AccountLifecycleEventUpsertBulk) AddCreatedByUserID(v int64) *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.AddCreatedByUserID(v)
	})
}

// UpdateCreatedByUserID sets the "created_by_user_id" field to the value that was provided on create.
func (u *AccountLifecycleEventUpsertBulk) UpdateCreatedByUserID() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.UpdateCreatedByUserID()
	})
}

// ClearCreatedByUserID clears the value of the "created_by_user_id" field.
func (u *AccountLifecycleEventUpsertBulk) ClearCreatedByUserID() *AccountLifecycleEventUpsertBulk {
	return u.Update(func(s *AccountLifecycleEventUpsert) {
		s.ClearCreatedByUserID()
	})
}

// Exec executes the query.
func (u *AccountLifecycleEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountLifecycleEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountLifecycleEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountLifecycleEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
