// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcostentry"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountCostEntryDelete is the builder for deleting a AccountCostEntry entity.
type AccountCostEntryDelete struct {
	config
	hooks    []Hook
	mutation *AccountCostEntryMutation
}

// Where appends a list predicates to the AccountCostEntryDelete builder.
func (_d *AccountCostEntryDelete) Where(ps ...predicate.AccountCostEntry) *AccountCostEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountCostEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountCostEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountCostEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountcostentry.Table, sqlgraph.NewFieldSpec(accountcostentry.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountCostEntryDeleteOne is the builder for deleting a single AccountCostEntry entity.
type AccountCostEntryDeleteOne struct {
	_d *AccountCostEntryDelete
}

// Where appends a list predicates to the AccountCostEntryDelete builder.
func (_d *AccountCostEntryDeleteOne) Where(ps ...predicate.AccountCostEntry) *AccountCostEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountCostEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountcostentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountCostEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
