// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcostentry"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountCostEntryUpdate is the builder for updating AccountCostEntry entities.
type AccountCostEntryUpdate struct {
	config
	hooks    []Hook
	mutation *AccountCostEntryMutation
}

// Where appends a list predicates to the AccountCostEntryUpdate builder.
func (_u *AccountCostEntryUpdate) Where(ps ...predicate.AccountCostEntry) *AccountCostEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountCostEntryUpdate) SetUpdatedAt(v time.Time) *AccountCostEntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountCostEntryUpdate) SetAccountID(v int64) *AccountCostEntryUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableAccountID(v *int64) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountCostEntryUpdate) AddAccountID(v int64) *AccountCostEntryUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetPayerUserID sets the "payer_user_id" field.
func (_u *AccountCostEntryUpdate) SetPayerUserID(v int64) *AccountCostEntryUpdate {
	_u.mutation.ResetPayerUserID()
	_u.mutation.SetPayerUserID(v)
	return _u
}

// SetNillablePayerUserID sets the "payer_user_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillablePayerUserID(v *int64) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetPayerUserID(*v)
	}
	return _u
}

// AddPayerUserID adds value to the "payer_user_id" field.
func (_u *AccountCostEntryUpdate) AddPayerUserID(v int64) *AccountCostEntryUpdate {
	_u.mutation.AddPayerUserID(v)
	return _u
}

// SetPurchaseSourceID sets the "purchase_source_id" field.
func (_u *AccountCostEntryUpdate) SetPurchaseSourceID(v int64) *AccountCostEntryUpdate {
	_u.mutation.ResetPurchaseSourceID()
	_u.mutation.SetPurchaseSourceID(v)
	return _u
}

// SetNillablePurchaseSourceID sets the "purchase_source_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillablePurchaseSourceID(v *int64) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetPurchaseSourceID(*v)
	}
	return _u
}

// AddPurchaseSourceID adds value to the "purchase_source_id" field.
func (_u *AccountCostEntryUpdate) AddPurchaseSourceID(v int64) *AccountCostEntryUpdate {
	_u.mutation.AddPurchaseSourceID(v)
	return _u
}

// ClearPurchaseSourceID clears the value of the "purchase_source_id" field.
func (_u *AccountCostEntryUpdate) ClearPurchaseSourceID() *AccountCostEntryUpdate {
	_u.mutation.ClearPurchaseSourceID()
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *AccountCostEntryUpdate) SetEntryType(v string) *AccountCostEntryUpdate {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableEntryType(v *string) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *AccountCostEntryUpdate) SetCurrency(v string) *AccountCostEntryUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableCurrency(v *string) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetOriginalAmount sets the "original_amount" field.
func (_u *AccountCostEntryUpdate) SetOriginalAmount(v string) *AccountCostEntryUpdate {
	_u.mutation.SetOriginalAmount(v)
	return _u
}

// SetNillableOriginalAmount sets the "original_amount" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableOriginalAmount(v *string) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetOriginalAmount(*v)
	}
	return _u
}

// SetCnyAmountMinor sets the "cny_amount_minor" field.
func (_u *AccountCostEntryUpdate) SetCnyAmountMinor(v int64) *AccountCostEntryUpdate {
	_u.mutation.ResetCnyAmountMinor()
	_u.mutation.SetCnyAmountMinor(v)
	return _u
}

// SetNillableCnyAmountMinor sets the "cny_amount_minor" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableCnyAmountMinor(v *int64) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetCnyAmountMinor(*v)
	}
	return _u
}

// AddCnyAmountMinor adds value to the "cny_amount_minor" field.
func (_u *AccountCostEntryUpdate) AddCnyAmountMinor(v int64) *AccountCostEntryUpdate {
	_u.mutation.AddCnyAmountMinor(v)
	return _u
}

// SetFxRate sets the "fx_rate" field.
func (_u *AccountCostEntryUpdate) SetFxRate(v string) *AccountCostEntryUpdate {
	_u.mutation.SetFxRate(v)
	return _u
}

// SetNillableFxRate sets the "fx_rate" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableFxRate(v *string) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetFxRate(*v)
	}
	return _u
}

// SetServiceStart sets the "service_start" field.
func (_u *AccountCostEntryUpdate) SetServiceStart(v time.Time) *AccountCostEntryUpdate {
	_u.mutation.SetServiceStart(v)
	return _u
}

// SetNillableServiceStart sets the "service_start" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableServiceStart(v *time.Time) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetServiceStart(*v)
	}
	return _u
}

// SetServiceEnd sets the "service_end" field.
func (_u *AccountCostEntryUpdate) SetServiceEnd(v time.Time) *AccountCostEntryUpdate {
	_u.mutation.SetServiceEnd(v)
	return _u
}

// SetNillableServiceEnd sets the "service_end" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableServiceEnd(v *time.Time) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetServiceEnd(*v)
	}
	return _u
}

// SetWarrantyEnd sets the "warranty_end" field.
func (_u *AccountCostEntryUpdate) SetWarrantyEnd(v time.Time) *AccountCostEntryUpdate {
	_u.mutation.SetWarrantyEnd(v)
	return _u
}

// SetNillableWarrantyEnd sets the "warranty_end" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableWarrantyEnd(v *time.Time) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetWarrantyEnd(*v)
	}
	return _u
}

// ClearWarrantyEnd clears the value of the "warranty_end" field.
func (_u *AccountCostEntryUpdate) ClearWarrantyEnd() *AccountCostEntryUpdate {
	_u.mutation.ClearWarrantyEnd()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *AccountCostEntryUpdate) SetPaidAt(v time.Time) *AccountCostEntryUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillablePaidAt(v *time.Time) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *AccountCostEntryUpdate) SetOrderNo(v string) *AccountCostEntryUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableOrderNo(v *string) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// ClearOrderNo clears the value of the "order_no" field.
func (_u *AccountCostEntryUpdate) ClearOrderNo() *AccountCostEntryUpdate {
	_u.mutation.ClearOrderNo()
	return _u
}

// SetPurchaseURL sets the "purchase_url" field.
func (_u *AccountCostEntryUpdate) SetPurchaseURL(v string) *AccountCostEntryUpdate {
	_u.mutation.SetPurchaseURL(v)
	return _u
}

// SetNillablePurchaseURL sets the "purchase_url" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillablePurchaseURL(v *string) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetPurchaseURL(*v)
	}
	return _u
}

// ClearPurchaseURL clears the value of the "purchase_url" field.
func (_u *AccountCostEntryUpdate) ClearPurchaseURL() *AccountCostEntryUpdate {
	_u.mutation.ClearPurchaseURL()
	return _u
}

// SetNote sets the "note" field.
func (_u *AccountCostEntryUpdate) SetNote(v string) *AccountCostEntryUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableNote(v *string) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AccountCostEntryUpdate) ClearNote() *AccountCostEntryUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetSupersedesID sets the "supersedes_id" field.
func (_u *AccountCostEntryUpdate) SetSupersedesID(v int64) *AccountCostEntryUpdate {
	_u.mutation.ResetSupersedesID()
	_u.mutation.SetSupersedesID(v)
	return _u
}

// SetNillableSupersedesID sets the "supersedes_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableSupersedesID(v *int64) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetSupersedesID(*v)
	}
	return _u
}

// AddSupersedesID adds value to the "supersedes_id" field.
func (_u *AccountCostEntryUpdate) AddSupersedesID(v int64) *AccountCostEntryUpdate {
	_u.mutation.AddSupersedesID(v)
	return _u
}

// ClearSupersedesID clears the value of the "supersedes_id" field.
func (_u *AccountCostEntryUpdate) ClearSupersedesID() *AccountCostEntryUpdate {
	_u.mutation.ClearSupersedesID()
	return _u
}

// SetRelatedAccountID sets the "related_account_id" field.
func (_u *AccountCostEntryUpdate) SetRelatedAccountID(v int64) *AccountCostEntryUpdate {
	_u.mutation.ResetRelatedAccountID()
	_u.mutation.SetRelatedAccountID(v)
	return _u
}

// SetNillableRelatedAccountID sets the "related_account_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableRelatedAccountID(v *int64) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetRelatedAccountID(*v)
	}
	return _u
}

// AddRelatedAccountID adds value to the "related_account_id" field.
func (_u *AccountCostEntryUpdate) AddRelatedAccountID(v int64) *AccountCostEntryUpdate {
	_u.mutation.AddRelatedAccountID(v)
	return _u
}

// ClearRelatedAccountID clears the value of the "related_account_id" field.
func (_u *AccountCostEntryUpdate) ClearRelatedAccountID() *AccountCostEntryUpdate {
	_u.mutation.ClearRelatedAccountID()
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *AccountCostEntryUpdate) SetCreatedByUserID(v int64) *AccountCostEntryUpdate {
	_u.mutation.ResetCreatedByUserID()
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdate) SetNillableCreatedByUserID(v *int64) *AccountCostEntryUpdate {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// AddCreatedByUserID adds value to the "created_by_user_id" field.
func (_u *AccountCostEntryUpdate) AddCreatedByUserID(v int64) *AccountCostEntryUpdate {
	_u.mutation.AddCreatedByUserID(v)
	return _u
}

// Mutation returns the AccountCostEntryMutation object of the builder.
func (_u *AccountCostEntryUpdate) Mutation() *AccountCostEntryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountCostEntryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountCostEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountCostEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountCostEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountCostEntryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountcostentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountCostEntryUpdate) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := accountcostentry.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := accountcostentry.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalAmount(); ok {
		if err := accountcostentry.OriginalAmountValidator(v); err != nil {
			return &ValidationError{Name: "original_amount", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.original_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FxRate(); ok {
		if err := accountcostentry.FxRateValidator(v); err != nil {
			return &ValidationError{Name: "fx_rate", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.fx_rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := accountcostentry.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PurchaseURL(); ok {
		if err := accountcostentry.PurchaseURLValidator(v); err != nil {
			return &ValidationError{Name: "purchase_url", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.purchase_url": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountCostEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountcostentry.Table, accountcostentry.Columns, sqlgraph.NewFieldSpec(accountcostentry.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountcostentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountcostentry.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountcostentry.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PayerUserID(); ok {
		_spec.SetField(accountcostentry.FieldPayerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayerUserID(); ok {
		_spec.AddField(accountcostentry.FieldPayerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PurchaseSourceID(); ok {
		_spec.SetField(accountcostentry.FieldPurchaseSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPurchaseSourceID(); ok {
		_spec.AddField(accountcostentry.FieldPurchaseSourceID, field.TypeInt64, value)
	}
	if _u.mutation.PurchaseSourceIDCleared() {
		_spec.ClearField(accountcostentry.FieldPurchaseSourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(accountcostentry.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(accountcostentry.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalAmount(); ok {
		_spec.SetField(accountcostentry.FieldOriginalAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.CnyAmountMinor(); ok {
		_spec.SetField(accountcostentry.FieldCnyAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCnyAmountMinor(); ok {
		_spec.AddField(accountcostentry.FieldCnyAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FxRate(); ok {
		_spec.SetField(accountcostentry.FieldFxRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceStart(); ok {
		_spec.SetField(accountcostentry.FieldServiceStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ServiceEnd(); ok {
		_spec.SetField(accountcostentry.FieldServiceEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WarrantyEnd(); ok {
		_spec.SetField(accountcostentry.FieldWarrantyEnd, field.TypeTime, value)
	}
	if _u.mutation.WarrantyEndCleared() {
		_spec.ClearField(accountcostentry.FieldWarrantyEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(accountcostentry.FieldPaidAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(accountcostentry.FieldOrderNo, field.TypeString, value)
	}
	if _u.mutation.OrderNoCleared() {
		_spec.ClearField(accountcostentry.FieldOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.PurchaseURL(); ok {
		_spec.SetField(accountcostentry.FieldPurchaseURL, field.TypeString, value)
	}
	if _u.mutation.PurchaseURLCleared() {
		_spec.ClearField(accountcostentry.FieldPurchaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(accountcostentry.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(accountcostentry.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.SupersedesID(); ok {
		_spec.SetField(accountcostentry.FieldSupersedesID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSupersedesID(); ok {
		_spec.AddField(accountcostentry.FieldSupersedesID, field.TypeInt64, value)
	}
	if _u.mutation.SupersedesIDCleared() {
		_spec.ClearField(accountcostentry.FieldSupersedesID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RelatedAccountID(); ok {
		_spec.SetField(accountcostentry.FieldRelatedAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRelatedAccountID(); ok {
		_spec.AddField(accountcostentry.FieldRelatedAccountID, field.TypeInt64, value)
	}
	if _u.mutation.RelatedAccountIDCleared() {
		_spec.ClearField(accountcostentry.FieldRelatedAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedByUserID(); ok {
		_spec.SetField(accountcostentry.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByUserID(); ok {
		_spec.AddField(accountcostentry.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountcostentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountCostEntryUpdateOne is the builder for updating a single AccountCostEntry entity.
type AccountCostEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountCostEntryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountCostEntryUpdateOne) SetUpdatedAt(v time.Time) *AccountCostEntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountCostEntryUpdateOne) SetAccountID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableAccountID(v *int64) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountCostEntryUpdateOne) AddAccountID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetPayerUserID sets the "payer_user_id" field.
func (_u *AccountCostEntryUpdateOne) SetPayerUserID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.ResetPayerUserID()
	_u.mutation.SetPayerUserID(v)
	return _u
}

// SetNillablePayerUserID sets the "payer_user_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillablePayerUserID(v *int64) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetPayerUserID(*v)
	}
	return _u
}

// AddPayerUserID adds value to the "payer_user_id" field.
func (_u *AccountCostEntryUpdateOne) AddPayerUserID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.AddPayerUserID(v)
	return _u
}

// SetPurchaseSourceID sets the "purchase_source_id" field.
func (_u *AccountCostEntryUpdateOne) SetPurchaseSourceID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.ResetPurchaseSourceID()
	_u.mutation.SetPurchaseSourceID(v)
	return _u
}

// SetNillablePurchaseSourceID sets the "purchase_source_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillablePurchaseSourceID(v *int64) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetPurchaseSourceID(*v)
	}
	return _u
}

// AddPurchaseSourceID adds value to the "purchase_source_id" field.
func (_u *AccountCostEntryUpdateOne) AddPurchaseSourceID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.AddPurchaseSourceID(v)
	return _u
}

// ClearPurchaseSourceID clears the value of the "purchase_source_id" field.
func (_u *AccountCostEntryUpdateOne) ClearPurchaseSourceID() *AccountCostEntryUpdateOne {
	_u.mutation.ClearPurchaseSourceID()
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *AccountCostEntryUpdateOne) SetEntryType(v string) *AccountCostEntryUpdateOne {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableEntryType(v *string) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *AccountCostEntryUpdateOne) SetCurrency(v string) *AccountCostEntryUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableCurrency(v *string) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetOriginalAmount sets the "original_amount" field.
func (_u *AccountCostEntryUpdateOne) SetOriginalAmount(v string) *AccountCostEntryUpdateOne {
	_u.mutation.SetOriginalAmount(v)
	return _u
}

// SetNillableOriginalAmount sets the "original_amount" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableOriginalAmount(v *string) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetOriginalAmount(*v)
	}
	return _u
}

// SetCnyAmountMinor sets the "cny_amount_minor" field.
func (_u *AccountCostEntryUpdateOne) SetCnyAmountMinor(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.ResetCnyAmountMinor()
	_u.mutation.SetCnyAmountMinor(v)
	return _u
}

// SetNillableCnyAmountMinor sets the "cny_amount_minor" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableCnyAmountMinor(v *int64) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetCnyAmountMinor(*v)
	}
	return _u
}

// AddCnyAmountMinor adds value to the "cny_amount_minor" field.
func (_u *AccountCostEntryUpdateOne) AddCnyAmountMinor(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.AddCnyAmountMinor(v)
	return _u
}

// SetFxRate sets the "fx_rate" field.
func (_u *AccountCostEntryUpdateOne) SetFxRate(v string) *AccountCostEntryUpdateOne {
	_u.mutation.SetFxRate(v)
	return _u
}

// SetNillableFxRate sets the "fx_rate" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableFxRate(v *string) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetFxRate(*v)
	}
	return _u
}

// SetServiceStart sets the "service_start" field.
func (_u *AccountCostEntryUpdateOne) SetServiceStart(v time.Time) *AccountCostEntryUpdateOne {
	_u.mutation.SetServiceStart(v)
	return _u
}

// SetNillableServiceStart sets the "service_start" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableServiceStart(v *time.Time) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetServiceStart(*v)
	}
	return _u
}

// SetServiceEnd sets the "service_end" field.
func (_u *AccountCostEntryUpdateOne) SetServiceEnd(v time.Time) *AccountCostEntryUpdateOne {
	_u.mutation.SetServiceEnd(v)
	return _u
}

// SetNillableServiceEnd sets the "service_end" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableServiceEnd(v *time.Time) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetServiceEnd(*v)
	}
	return _u
}

// SetWarrantyEnd sets the "warranty_end" field.
func (_u *AccountCostEntryUpdateOne) SetWarrantyEnd(v time.Time) *AccountCostEntryUpdateOne {
	_u.mutation.SetWarrantyEnd(v)
	return _u
}

// SetNillableWarrantyEnd sets the "warranty_end" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableWarrantyEnd(v *time.Time) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetWarrantyEnd(*v)
	}
	return _u
}

// ClearWarrantyEnd clears the value of the "warranty_end" field.
func (_u *AccountCostEntryUpdateOne) ClearWarrantyEnd() *AccountCostEntryUpdateOne {
	_u.mutation.ClearWarrantyEnd()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *AccountCostEntryUpdateOne) SetPaidAt(v time.Time) *AccountCostEntryUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillablePaidAt(v *time.Time) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *AccountCostEntryUpdateOne) SetOrderNo(v string) *AccountCostEntryUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableOrderNo(v *string) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// ClearOrderNo clears the value of the "order_no" field.
func (_u *AccountCostEntryUpdateOne) ClearOrderNo() *AccountCostEntryUpdateOne {
	_u.mutation.ClearOrderNo()
	return _u
}

// SetPurchaseURL sets the "purchase_url" field.
func (_u *AccountCostEntryUpdateOne) SetPurchaseURL(v string) *AccountCostEntryUpdateOne {
	_u.mutation.SetPurchaseURL(v)
	return _u
}

// SetNillablePurchaseURL sets the "purchase_url" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillablePurchaseURL(v *string) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetPurchaseURL(*v)
	}
	return _u
}

// ClearPurchaseURL clears the value of the "purchase_url" field.
func (_u *AccountCostEntryUpdateOne) ClearPurchaseURL() *AccountCostEntryUpdateOne {
	_u.mutation.ClearPurchaseURL()
	return _u
}

// SetNote sets the "note" field.
func (_u *AccountCostEntryUpdateOne) SetNote(v string) *AccountCostEntryUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableNote(v *string) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AccountCostEntryUpdateOne) ClearNote() *AccountCostEntryUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetSupersedesID sets the "supersedes_id" field.
func (_u *AccountCostEntryUpdateOne) SetSupersedesID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.ResetSupersedesID()
	_u.mutation.SetSupersedesID(v)
	return _u
}

// SetNillableSupersedesID sets the "supersedes_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableSupersedesID(v *int64) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetSupersedesID(*v)
	}
	return _u
}

// AddSupersedesID adds value to the "supersedes_id" field.
func (_u *AccountCostEntryUpdateOne) AddSupersedesID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.AddSupersedesID(v)
	return _u
}

// ClearSupersedesID clears the value of the "supersedes_id" field.
func (_u *AccountCostEntryUpdateOne) ClearSupersedesID() *AccountCostEntryUpdateOne {
	_u.mutation.ClearSupersedesID()
	return _u
}

// SetRelatedAccountID sets the "related_account_id" field.
func (_u *AccountCostEntryUpdateOne) SetRelatedAccountID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.ResetRelatedAccountID()
	_u.mutation.SetRelatedAccountID(v)
	return _u
}

// SetNillableRelatedAccountID sets the "related_account_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableRelatedAccountID(v *int64) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetRelatedAccountID(*v)
	}
	return _u
}

// AddRelatedAccountID adds value to the "related_account_id" field.
func (_u *AccountCostEntryUpdateOne) AddRelatedAccountID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.AddRelatedAccountID(v)
	return _u
}

// ClearRelatedAccountID clears the value of the "related_account_id" field.
func (_u *AccountCostEntryUpdateOne) ClearRelatedAccountID() *AccountCostEntryUpdateOne {
	_u.mutation.ClearRelatedAccountID()
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *AccountCostEntryUpdateOne) SetCreatedByUserID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.ResetCreatedByUserID()
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *AccountCostEntryUpdateOne) SetNillableCreatedByUserID(v *int64) *AccountCostEntryUpdateOne {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// AddCreatedByUserID adds value to the "created_by_user_id" field.
func (_u *AccountCostEntryUpdateOne) AddCreatedByUserID(v int64) *AccountCostEntryUpdateOne {
	_u.mutation.AddCreatedByUserID(v)
	return _u
}

// Mutation returns the AccountCostEntryMutation object of the builder.
func (_u *AccountCostEntryUpdateOne) Mutation() *AccountCostEntryMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountCostEntryUpdate builder.
func (_u *AccountCostEntryUpdateOne) Where(ps ...predicate.AccountCostEntry) *AccountCostEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountCostEntryUpdateOne) Select(field string, fields ...string) *AccountCostEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountCostEntry entity.
func (_u *AccountCostEntryUpdateOne) Save(ctx context.Context) (*AccountCostEntry, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountCostEntryUpdateOne) SaveX(ctx context.Context) *AccountCostEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountCostEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountCostEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountCostEntryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountcostentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountCostEntryUpdateOne) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := accountcostentry.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := accountcostentry.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalAmount(); ok {
		if err := accountcostentry.OriginalAmountValidator(v); err != nil {
			return &ValidationError{Name: "original_amount", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.original_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FxRate(); ok {
		if err := accountcostentry.FxRateValidator(v); err != nil {
			return &ValidationError{Name: "fx_rate", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.fx_rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := accountcostentry.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PurchaseURL(); ok {
		if err := accountcostentry.PurchaseURLValidator(v); err != nil {
			return &ValidationError{Name: "purchase_url", err: fmt.Errorf(`ent: validator failed for field "AccountCostEntry.purchase_url": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountCostEntryUpdateOne) sqlSave(ctx context.Context) (_node *AccountCostEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountcostentry.Table, accountcostentry.Columns, sqlgraph.NewFieldSpec(accountcostentry.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountCostEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountcostentry.FieldID)
		for _, f := range fields {
			if !accountcostentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountcostentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountcostentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountcostentry.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountcostentry.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PayerUserID(); ok {
		_spec.SetField(accountcostentry.FieldPayerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayerUserID(); ok {
		_spec.AddField(accountcostentry.FieldPayerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PurchaseSourceID(); ok {
		_spec.SetField(accountcostentry.FieldPurchaseSourceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPurchaseSourceID(); ok {
		_spec.AddField(accountcostentry.FieldPurchaseSourceID, field.TypeInt64, value)
	}
	if _u.mutation.PurchaseSourceIDCleared() {
		_spec.ClearField(accountcostentry.FieldPurchaseSourceID, field.TypeInt64)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(accountcostentry.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(accountcostentry.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalAmount(); ok {
		_spec.SetField(accountcostentry.FieldOriginalAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.CnyAmountMinor(); ok {
		_spec.SetField(accountcostentry.FieldCnyAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCnyAmountMinor(); ok {
		_spec.AddField(accountcostentry.FieldCnyAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FxRate(); ok {
		_spec.SetField(accountcostentry.FieldFxRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceStart(); ok {
		_spec.SetField(accountcostentry.FieldServiceStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ServiceEnd(); ok {
		_spec.SetField(accountcostentry.FieldServiceEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WarrantyEnd(); ok {
		_spec.SetField(accountcostentry.FieldWarrantyEnd, field.TypeTime, value)
	}
	if _u.mutation.WarrantyEndCleared() {
		_spec.ClearField(accountcostentry.FieldWarrantyEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(accountcostentry.FieldPaidAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(accountcostentry.FieldOrderNo, field.TypeString, value)
	}
	if _u.mutation.OrderNoCleared() {
		_spec.ClearField(accountcostentry.FieldOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.PurchaseURL(); ok {
		_spec.SetField(accountcostentry.FieldPurchaseURL, field.TypeString, value)
	}
	if _u.mutation.PurchaseURLCleared() {
		_spec.ClearField(accountcostentry.FieldPurchaseURL, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(accountcostentry.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(accountcostentry.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.SupersedesID(); ok {
		_spec.SetField(accountcostentry.FieldSupersedesID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSupersedesID(); ok {
		_spec.AddField(accountcostentry.FieldSupersedesID, field.TypeInt64, value)
	}
	if _u.mutation.SupersedesIDCleared() {
		_spec.ClearField(accountcostentry.FieldSupersedesID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RelatedAccountID(); ok {
		_spec.SetField(accountcostentry.FieldRelatedAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRelatedAccountID(); ok {
		_spec.AddField(accountcostentry.FieldRelatedAccountID, field.TypeInt64, value)
	}
	if _u.mutation.RelatedAccountIDCleared() {
		_spec.ClearField(accountcostentry.FieldRelatedAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedByUserID(); ok {
		_spec.SetField(accountcostentry.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByUserID(); ok {
		_spec.AddField(accountcostentry.FieldCreatedByUserID, field.TypeInt64, value)
	}
	_node = &AccountCostEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountcostentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
