// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountlifecycleevent"
)

// AccountLifecycleEvent is the model entity for the AccountLifecycleEvent schema.
type AccountLifecycleEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// ReplacementAccountID holds the value of the "replacement_account_id" field.
	ReplacementAccountID *int64 `json:"replacement_account_id,omitempty"`
	// TransferredCostMinor holds the value of the "transferred_cost_minor" field.
	TransferredCostMinor int64 `json:"transferred_cost_minor,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID *int64 `json:"created_by_user_id,omitempty"`
	selectValues    sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountLifecycleEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountlifecycleevent.FieldID, accountlifecycleevent.FieldAccountID, accountlifecycleevent.FieldReplacementAccountID, accountlifecycleevent.FieldTransferredCostMinor, accountlifecycleevent.FieldCreatedByUserID:
			values[i] = new(sql.NullInt64)
		case accountlifecycleevent.FieldEventType, accountlifecycleevent.FieldReason, accountlifecycleevent.FieldSource:
			values[i] = new(sql.NullString)
		case accountlifecycleevent.FieldCreatedAt, accountlifecycleevent.FieldUpdatedAt, accountlifecycleevent.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountLifecycleEvent fields.
func (_m *AccountLifecycleEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountlifecycleevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountlifecycleevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountlifecycleevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountlifecycleevent.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountlifecycleevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case accountlifecycleevent.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		case accountlifecycleevent.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case accountlifecycleevent.FieldReplacementAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field replacement_account_id", values[i])
			} else if value.Valid {
				_m.ReplacementAccountID = new(int64)
				*_m.ReplacementAccountID = value.Int64
			}
		case accountlifecycleevent.FieldTransferredCostMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transferred_cost_minor", values[i])
			} else if value.Valid {
				_m.TransferredCostMinor = value.Int64
			}
		case accountlifecycleevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case accountlifecycleevent.FieldCreatedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value.Valid {
				_m.CreatedByUserID = new(int64)
				*_m.CreatedByUserID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountLifecycleEvent.
// This includes values selected through modifiers, order, etc.
func (_m *AccountLifecycleEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountLifecycleEvent.
// Note that you need to call AccountLifecycleEvent.Unwrap() before calling this method if this AccountLifecycleEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountLifecycleEvent) Update() *AccountLifecycleEventUpdateOne {
	return NewAccountLifecycleEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountLifecycleEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountLifecycleEvent) Unwrap() *AccountLifecycleEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountLifecycleEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountLifecycleEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AccountLifecycleEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReplacementAccountID; v != nil {
		builder.WriteString("replacement_account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("transferred_cost_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.TransferredCostMinor))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.CreatedByUserID; v != nil {
		builder.WriteString("created_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AccountLifecycleEvents is a parsable slice of AccountLifecycleEvent.
type AccountLifecycleEvents []*AccountLifecycleEvent
