// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/poolsettlementline"
)

// PoolSettlementLine is the model entity for the PoolSettlementLine schema.
type PoolSettlementLine struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SettlementID holds the value of the "settlement_id" field.
	SettlementID int64 `json:"settlement_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// UsageWeight holds the value of the "usage_weight" field.
	UsageWeight string `json:"usage_weight,omitempty"`
	// UsageShare holds the value of the "usage_share" field.
	UsageShare string `json:"usage_share,omitempty"`
	// AllocatedCostMinor holds the value of the "allocated_cost_minor" field.
	AllocatedCostMinor int64 `json:"allocated_cost_minor,omitempty"`
	// ContributionCreditMinor holds the value of the "contribution_credit_minor" field.
	ContributionCreditMinor int64 `json:"contribution_credit_minor,omitempty"`
	// AdjustmentMinor holds the value of the "adjustment_minor" field.
	AdjustmentMinor int64 `json:"adjustment_minor,omitempty"`
	// NetAmountMinor holds the value of the "net_amount_minor" field.
	NetAmountMinor int64 `json:"net_amount_minor,omitempty"`
	// PaymentStatus holds the value of the "payment_status" field.
	PaymentStatus string `json:"payment_status,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PoolSettlementLine) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case poolsettlementline.FieldID, poolsettlementline.FieldSettlementID, poolsettlementline.FieldUserID, poolsettlementline.FieldAllocatedCostMinor, poolsettlementline.FieldContributionCreditMinor, poolsettlementline.FieldAdjustmentMinor, poolsettlementline.FieldNetAmountMinor:
			values[i] = new(sql.NullInt64)
		case poolsettlementline.FieldUsageWeight, poolsettlementline.FieldUsageShare, poolsettlementline.FieldPaymentStatus:
			values[i] = new(sql.NullString)
		case poolsettlementline.FieldCreatedAt, poolsettlementline.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PoolSettlementLine fields.
func (_m *PoolSettlementLine) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case poolsettlementline.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case poolsettlementline.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case poolsettlementline.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case poolsettlementline.FieldSettlementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_id", values[i])
			} else if value.Valid {
				_m.SettlementID = value.Int64
			}
		case poolsettlementline.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case poolsettlementline.FieldUsageWeight:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_weight", values[i])
			} else if value.Valid {
				_m.UsageWeight = value.String
			}
		case poolsettlementline.FieldUsageShare:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_share", values[i])
			} else if value.Valid {
				_m.UsageShare = value.String
			}
		case poolsettlementline.FieldAllocatedCostMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field allocated_cost_minor", values[i])
			} else if value.Valid {
				_m.AllocatedCostMinor = value.Int64
			}
		case poolsettlementline.FieldContributionCreditMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field contribution_credit_minor", values[i])
			} else if value.Valid {
				_m.ContributionCreditMinor = value.Int64
			}
		case poolsettlementline.FieldAdjustmentMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field adjustment_minor", values[i])
			} else if value.Valid {
				_m.AdjustmentMinor = value.Int64
			}
		case poolsettlementline.FieldNetAmountMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field net_amount_minor", values[i])
			} else if value.Valid {
				_m.NetAmountMinor = value.Int64
			}
		case poolsettlementline.FieldPaymentStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_status", values[i])
			} else if value.Valid {
				_m.PaymentStatus = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PoolSettlementLine.
// This includes values selected through modifiers, order, etc.
func (_m *PoolSettlementLine) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PoolSettlementLine.
// Note that you need to call PoolSettlementLine.Unwrap() before calling this method if this PoolSettlementLine
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PoolSettlementLine) Update() *PoolSettlementLineUpdateOne {
	return NewPoolSettlementLineClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PoolSettlementLine entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PoolSettlementLine) Unwrap() *PoolSettlementLine {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PoolSettlementLine is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PoolSettlementLine) String() string {
	var builder strings.Builder
	builder.WriteString("PoolSettlementLine(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("settlement_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettlementID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("usage_weight=")
	builder.WriteString(_m.UsageWeight)
	builder.WriteString(", ")
	builder.WriteString("usage_share=")
	builder.WriteString(_m.UsageShare)
	builder.WriteString(", ")
	builder.WriteString("allocated_cost_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllocatedCostMinor))
	builder.WriteString(", ")
	builder.WriteString("contribution_credit_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContributionCreditMinor))
	builder.WriteString(", ")
	builder.WriteString("adjustment_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdjustmentMinor))
	builder.WriteString(", ")
	builder.WriteString("net_amount_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetAmountMinor))
	builder.WriteString(", ")
	builder.WriteString("payment_status=")
	builder.WriteString(_m.PaymentStatus)
	builder.WriteByte(')')
	return builder.String()
}

// PoolSettlementLines is a parsable slice of PoolSettlementLine.
type PoolSettlementLines []*PoolSettlementLine
