// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/poolsettlement"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PoolSettlementUpdate is the builder for updating PoolSettlement entities.
type PoolSettlementUpdate struct {
	config
	hooks    []Hook
	mutation *PoolSettlementMutation
}

// Where appends a list predicates to the PoolSettlementUpdate builder.
func (_u *PoolSettlementUpdate) Where(ps ...predicate.PoolSettlement) *PoolSettlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PoolSettlementUpdate) SetUpdatedAt(v time.Time) *PoolSettlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPeriodType sets the "period_type" field.
func (_u *PoolSettlementUpdate) SetPeriodType(v string) *PoolSettlementUpdate {
	_u.mutation.SetPeriodType(v)
	return _u
}

// SetNillablePeriodType sets the "period_type" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillablePeriodType(v *string) *PoolSettlementUpdate {
	if v != nil {
		_u.SetPeriodType(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *PoolSettlementUpdate) SetPeriodStart(v time.Time) *PoolSettlementUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillablePeriodStart(v *time.Time) *PoolSettlementUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *PoolSettlementUpdate) SetPeriodEnd(v time.Time) *PoolSettlementUpdate {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillablePeriodEnd(v *time.Time) *PoolSettlementUpdate {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *PoolSettlementUpdate) SetTimezone(v string) *PoolSettlementUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableTimezone(v *string) *PoolSettlementUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PoolSettlementUpdate) SetStatus(v string) *PoolSettlementUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableStatus(v *string) *PoolSettlementUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPeriodCostMinor sets the "period_cost_minor" field.
func (_u *PoolSettlementUpdate) SetPeriodCostMinor(v int64) *PoolSettlementUpdate {
	_u.mutation.ResetPeriodCostMinor()
	_u.mutation.SetPeriodCostMinor(v)
	return _u
}

// SetNillablePeriodCostMinor sets the "period_cost_minor" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillablePeriodCostMinor(v *int64) *PoolSettlementUpdate {
	if v != nil {
		_u.SetPeriodCostMinor(*v)
	}
	return _u
}

// AddPeriodCostMinor adds value to the "period_cost_minor" field.
func (_u *PoolSettlementUpdate) AddPeriodCostMinor(v int64) *PoolSettlementUpdate {
	_u.mutation.AddPeriodCostMinor(v)
	return _u
}

// SetCarryInMinor sets the "carry_in_minor" field.
func (_u *PoolSettlementUpdate) SetCarryInMinor(v int64) *PoolSettlementUpdate {
	_u.mutation.ResetCarryInMinor()
	_u.mutation.SetCarryInMinor(v)
	return _u
}

// SetNillableCarryInMinor sets the "carry_in_minor" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableCarryInMinor(v *int64) *PoolSettlementUpdate {
	if v != nil {
		_u.SetCarryInMinor(*v)
	}
	return _u
}

// AddCarryInMinor adds value to the "carry_in_minor" field.
func (_u *PoolSettlementUpdate) AddCarryInMinor(v int64) *PoolSettlementUpdate {
	_u.mutation.AddCarryInMinor(v)
	return _u
}

// SetCarryOutMinor sets the "carry_out_minor" field.
func (_u *PoolSettlementUpdate) SetCarryOutMinor(v int64) *PoolSettlementUpdate {
	_u.mutation.ResetCarryOutMinor()
	_u.mutation.SetCarryOutMinor(v)
	return _u
}

// SetNillableCarryOutMinor sets the "carry_out_minor" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableCarryOutMinor(v *int64) *PoolSettlementUpdate {
	if v != nil {
		_u.SetCarryOutMinor(*v)
	}
	return _u
}

// AddCarryOutMinor adds value to the "carry_out_minor" field.
func (_u *PoolSettlementUpdate) AddCarryOutMinor(v int64) *PoolSettlementUpdate {
	_u.mutation.AddCarryOutMinor(v)
	return _u
}

// SetTotalCostMinor sets the "total_cost_minor" field.
func (_u *PoolSettlementUpdate) SetTotalCostMinor(v int64) *PoolSettlementUpdate {
	_u.mutation.ResetTotalCostMinor()
	_u.mutation.SetTotalCostMinor(v)
	return _u
}

// SetNillableTotalCostMinor sets the "total_cost_minor" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableTotalCostMinor(v *int64) *PoolSettlementUpdate {
	if v != nil {
		_u.SetTotalCostMinor(*v)
	}
	return _u
}

// AddTotalCostMinor adds value to the "total_cost_minor" field.
func (_u *PoolSettlementUpdate) AddTotalCostMinor(v int64) *PoolSettlementUpdate {
	_u.mutation.AddTotalCostMinor(v)
	return _u
}

// SetTotalUsageWeight sets the "total_usage_weight" field.
func (_u *PoolSettlementUpdate) SetTotalUsageWeight(v string) *PoolSettlementUpdate {
	_u.mutation.SetTotalUsageWeight(v)
	return _u
}

// SetNillableTotalUsageWeight sets the "total_usage_weight" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableTotalUsageWeight(v *string) *PoolSettlementUpdate {
	if v != nil {
		_u.SetTotalUsageWeight(*v)
	}
	return _u
}

// SetPricingCoverage sets the "pricing_coverage" field.
func (_u *PoolSettlementUpdate) SetPricingCoverage(v string) *PoolSettlementUpdate {
	_u.mutation.SetPricingCoverage(v)
	return _u
}

// SetNillablePricingCoverage sets the "pricing_coverage" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillablePricingCoverage(v *string) *PoolSettlementUpdate {
	if v != nil {
		_u.SetPricingCoverage(*v)
	}
	return _u
}

// SetUnpricedUsageCount sets the "unpriced_usage_count" field.
func (_u *PoolSettlementUpdate) SetUnpricedUsageCount(v int64) *PoolSettlementUpdate {
	_u.mutation.ResetUnpricedUsageCount()
	_u.mutation.SetUnpricedUsageCount(v)
	return _u
}

// SetNillableUnpricedUsageCount sets the "unpriced_usage_count" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableUnpricedUsageCount(v *int64) *PoolSettlementUpdate {
	if v != nil {
		_u.SetUnpricedUsageCount(*v)
	}
	return _u
}

// AddUnpricedUsageCount adds value to the "unpriced_usage_count" field.
func (_u *PoolSettlementUpdate) AddUnpricedUsageCount(v int64) *PoolSettlementUpdate {
	_u.mutation.AddUnpricedUsageCount(v)
	return _u
}

// SetFxRate sets the "fx_rate" field.
func (_u *PoolSettlementUpdate) SetFxRate(v string) *PoolSettlementUpdate {
	_u.mutation.SetFxRate(v)
	return _u
}

// SetNillableFxRate sets the "fx_rate" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableFxRate(v *string) *PoolSettlementUpdate {
	if v != nil {
		_u.SetFxRate(*v)
	}
	return _u
}

// SetFormulaVersion sets the "formula_version" field.
func (_u *PoolSettlementUpdate) SetFormulaVersion(v string) *PoolSettlementUpdate {
	_u.mutation.SetFormulaVersion(v)
	return _u
}

// SetNillableFormulaVersion sets the "formula_version" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableFormulaVersion(v *string) *PoolSettlementUpdate {
	if v != nil {
		_u.SetFormulaVersion(*v)
	}
	return _u
}

// SetCostSnapshot sets the "cost_snapshot" field.
func (_u *PoolSettlementUpdate) SetCostSnapshot(v []map[string]interface{}) *PoolSettlementUpdate {
	_u.mutation.SetCostSnapshot(v)
	return _u
}

// AppendCostSnapshot appends value to the "cost_snapshot" field.
func (_u *PoolSettlementUpdate) AppendCostSnapshot(v []map[string]interface{}) *PoolSettlementUpdate {
	_u.mutation.AppendCostSnapshot(v)
	return _u
}

// SetGeneratedByUserID sets the "generated_by_user_id" field.
func (_u *PoolSettlementUpdate) SetGeneratedByUserID(v int64) *PoolSettlementUpdate {
	_u.mutation.ResetGeneratedByUserID()
	_u.mutation.SetGeneratedByUserID(v)
	return _u
}

// SetNillableGeneratedByUserID sets the "generated_by_user_id" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableGeneratedByUserID(v *int64) *PoolSettlementUpdate {
	if v != nil {
		_u.SetGeneratedByUserID(*v)
	}
	return _u
}

// AddGeneratedByUserID adds value to the "generated_by_user_id" field.
func (_u *PoolSettlementUpdate) AddGeneratedByUserID(v int64) *PoolSettlementUpdate {
	_u.mutation.AddGeneratedByUserID(v)
	return _u
}

// SetLockedByUserID sets the "locked_by_user_id" field.
func (_u *PoolSettlementUpdate) SetLockedByUserID(v int64) *PoolSettlementUpdate {
	_u.mutation.ResetLockedByUserID()
	_u.mutation.SetLockedByUserID(v)
	return _u
}

// SetNillableLockedByUserID sets the "locked_by_user_id" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableLockedByUserID(v *int64) *PoolSettlementUpdate {
	if v != nil {
		_u.SetLockedByUserID(*v)
	}
	return _u
}

// AddLockedByUserID adds value to the "locked_by_user_id" field.
func (_u *PoolSettlementUpdate) AddLockedByUserID(v int64) *PoolSettlementUpdate {
	_u.mutation.AddLockedByUserID(v)
	return _u
}

// ClearLockedByUserID clears the value of the "locked_by_user_id" field.
func (_u *PoolSettlementUpdate) ClearLockedByUserID() *PoolSettlementUpdate {
	_u.mutation.ClearLockedByUserID()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *PoolSettlementUpdate) SetLockedAt(v time.Time) *PoolSettlementUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *PoolSettlementUpdate) SetNillableLockedAt(v *time.Time) *PoolSettlementUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *PoolSettlementUpdate) ClearLockedAt() *PoolSettlementUpdate {
	_u.mutation.ClearLockedAt()
	return _u
}

// Mutation returns the PoolSettlementMutation object of the builder.
func (_u *PoolSettlementUpdate) Mutation() *PoolSettlementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PoolSettlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PoolSettlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PoolSettlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PoolSettlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PoolSettlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := poolsettlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PoolSettlementUpdate) check() error {
	if v, ok := _u.mutation.PeriodType(); ok {
		if err := poolsettlement.PeriodTypeValidator(v); err != nil {
			return &ValidationError{Name: "period_type", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.period_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := poolsettlement.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := poolsettlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalUsageWeight(); ok {
		if err := poolsettlement.TotalUsageWeightValidator(v); err != nil {
			return &ValidationError{Name: "total_usage_weight", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.total_usage_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PricingCoverage(); ok {
		if err := poolsettlement.PricingCoverageValidator(v); err != nil {
			return &ValidationError{Name: "pricing_coverage", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.pricing_coverage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FxRate(); ok {
		if err := poolsettlement.FxRateValidator(v); err != nil {
			return &ValidationError{Name: "fx_rate", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.fx_rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FormulaVersion(); ok {
		if err := poolsettlement.FormulaVersionValidator(v); err != nil {
			return &ValidationError{Name: "formula_version", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.formula_version": %w`, err)}
		}
	}
	return nil
}

func (_u *PoolSettlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(poolsettlement.Table, poolsettlement.Columns, sqlgraph.NewFieldSpec(poolsettlement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(poolsettlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodType(); ok {
		_spec.SetField(poolsettlement.FieldPeriodType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(poolsettlement.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(poolsettlement.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(poolsettlement.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(poolsettlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodCostMinor(); ok {
		_spec.SetField(poolsettlement.FieldPeriodCostMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPeriodCostMinor(); ok {
		_spec.AddField(poolsettlement.FieldPeriodCostMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CarryInMinor(); ok {
		_spec.SetField(poolsettlement.FieldCarryInMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCarryInMinor(); ok {
		_spec.AddField(poolsettlement.FieldCarryInMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CarryOutMinor(); ok {
		_spec.SetField(poolsettlement.FieldCarryOutMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCarryOutMinor(); ok {
		_spec.AddField(poolsettlement.FieldCarryOutMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCostMinor(); ok {
		_spec.SetField(poolsettlement.FieldTotalCostMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalCostMinor(); ok {
		_spec.AddField(poolsettlement.FieldTotalCostMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalUsageWeight(); ok {
		_spec.SetField(poolsettlement.FieldTotalUsageWeight, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricingCoverage(); ok {
		_spec.SetField(poolsettlement.FieldPricingCoverage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnpricedUsageCount(); ok {
		_spec.SetField(poolsettlement.FieldUnpricedUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnpricedUsageCount(); ok {
		_spec.AddField(poolsettlement.FieldUnpricedUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FxRate(); ok {
		_spec.SetField(poolsettlement.FieldFxRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.FormulaVersion(); ok {
		_spec.SetField(poolsettlement.FieldFormulaVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostSnapshot(); ok {
		_spec.SetField(poolsettlement.FieldCostSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCostSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, poolsettlement.FieldCostSnapshot, value)
		})
	}
	if value, ok := _u.mutation.GeneratedByUserID(); ok {
		_spec.SetField(poolsettlement.FieldGeneratedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGeneratedByUserID(); ok {
		_spec.AddField(poolsettlement.FieldGeneratedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LockedByUserID(); ok {
		_spec.SetField(poolsettlement.FieldLockedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLockedByUserID(); ok {
		_spec.AddField(poolsettlement.FieldLockedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.LockedByUserIDCleared() {
		_spec.ClearField(poolsettlement.FieldLockedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(poolsettlement.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(poolsettlement.FieldLockedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{poolsettlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PoolSettlementUpdateOne is the builder for updating a single PoolSettlement entity.
type PoolSettlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PoolSettlementMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PoolSettlementUpdateOne) SetUpdatedAt(v time.Time) *PoolSettlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPeriodType sets the "period_type" field.
func (_u *PoolSettlementUpdateOne) SetPeriodType(v string) *PoolSettlementUpdateOne {
	_u.mutation.SetPeriodType(v)
	return _u
}

// SetNillablePeriodType sets the "period_type" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillablePeriodType(v *string) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetPeriodType(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *PoolSettlementUpdateOne) SetPeriodStart(v time.Time) *PoolSettlementUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillablePeriodStart(v *time.Time) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *PoolSettlementUpdateOne) SetPeriodEnd(v time.Time) *PoolSettlementUpdateOne {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillablePeriodEnd(v *time.Time) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *PoolSettlementUpdateOne) SetTimezone(v string) *PoolSettlementUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableTimezone(v *string) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PoolSettlementUpdateOne) SetStatus(v string) *PoolSettlementUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableStatus(v *string) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPeriodCostMinor sets the "period_cost_minor" field.
func (_u *PoolSettlementUpdateOne) SetPeriodCostMinor(v int64) *PoolSettlementUpdateOne {
	_u.mutation.ResetPeriodCostMinor()
	_u.mutation.SetPeriodCostMinor(v)
	return _u
}

// SetNillablePeriodCostMinor sets the "period_cost_minor" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillablePeriodCostMinor(v *int64) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetPeriodCostMinor(*v)
	}
	return _u
}

// AddPeriodCostMinor adds value to the "period_cost_minor" field.
func (_u *PoolSettlementUpdateOne) AddPeriodCostMinor(v int64) *PoolSettlementUpdateOne {
	_u.mutation.AddPeriodCostMinor(v)
	return _u
}

// SetCarryInMinor sets the "carry_in_minor" field.
func (_u *PoolSettlementUpdateOne) SetCarryInMinor(v int64) *PoolSettlementUpdateOne {
	_u.mutation.ResetCarryInMinor()
	_u.mutation.SetCarryInMinor(v)
	return _u
}

// SetNillableCarryInMinor sets the "carry_in_minor" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableCarryInMinor(v *int64) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetCarryInMinor(*v)
	}
	return _u
}

// AddCarryInMinor adds value to the "carry_in_minor" field.
func (_u *PoolSettlementUpdateOne) AddCarryInMinor(v int64) *PoolSettlementUpdateOne {
	_u.mutation.AddCarryInMinor(v)
	return _u
}

// SetCarryOutMinor sets the "carry_out_minor" field.
func (_u *PoolSettlementUpdateOne) SetCarryOutMinor(v int64) *PoolSettlementUpdateOne {
	_u.mutation.ResetCarryOutMinor()
	_u.mutation.SetCarryOutMinor(v)
	return _u
}

// SetNillableCarryOutMinor sets the "carry_out_minor" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableCarryOutMinor(v *int64) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetCarryOutMinor(*v)
	}
	return _u
}

// AddCarryOutMinor adds value to the "carry_out_minor" field.
func (_u *PoolSettlementUpdateOne) AddCarryOutMinor(v int64) *PoolSettlementUpdateOne {
	_u.mutation.AddCarryOutMinor(v)
	return _u
}

// SetTotalCostMinor sets the "total_cost_minor" field.
func (_u *PoolSettlementUpdateOne) SetTotalCostMinor(v int64) *PoolSettlementUpdateOne {
	_u.mutation.ResetTotalCostMinor()
	_u.mutation.SetTotalCostMinor(v)
	return _u
}

// SetNillableTotalCostMinor sets the "total_cost_minor" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableTotalCostMinor(v *int64) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetTotalCostMinor(*v)
	}
	return _u
}

// AddTotalCostMinor adds value to the "total_cost_minor" field.
func (_u *PoolSettlementUpdateOne) AddTotalCostMinor(v int64) *PoolSettlementUpdateOne {
	_u.mutation.AddTotalCostMinor(v)
	return _u
}

// SetTotalUsageWeight sets the "total_usage_weight" field.
func (_u *PoolSettlementUpdateOne) SetTotalUsageWeight(v string) *PoolSettlementUpdateOne {
	_u.mutation.SetTotalUsageWeight(v)
	return _u
}

// SetNillableTotalUsageWeight sets the "total_usage_weight" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableTotalUsageWeight(v *string) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetTotalUsageWeight(*v)
	}
	return _u
}

// SetPricingCoverage sets the "pricing_coverage" field.
func (_u *PoolSettlementUpdateOne) SetPricingCoverage(v string) *PoolSettlementUpdateOne {
	_u.mutation.SetPricingCoverage(v)
	return _u
}

// SetNillablePricingCoverage sets the "pricing_coverage" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillablePricingCoverage(v *string) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetPricingCoverage(*v)
	}
	return _u
}

// SetUnpricedUsageCount sets the "unpriced_usage_count" field.
func (_u *PoolSettlementUpdateOne) SetUnpricedUsageCount(v int64) *PoolSettlementUpdateOne {
	_u.mutation.ResetUnpricedUsageCount()
	_u.mutation.SetUnpricedUsageCount(v)
	return _u
}

// SetNillableUnpricedUsageCount sets the "unpriced_usage_count" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableUnpricedUsageCount(v *int64) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetUnpricedUsageCount(*v)
	}
	return _u
}

// AddUnpricedUsageCount adds value to the "unpriced_usage_count" field.
func (_u *PoolSettlementUpdateOne) AddUnpricedUsageCount(v int64) *PoolSettlementUpdateOne {
	_u.mutation.AddUnpricedUsageCount(v)
	return _u
}

// SetFxRate sets the "fx_rate" field.
func (_u *PoolSettlementUpdateOne) SetFxRate(v string) *PoolSettlementUpdateOne {
	_u.mutation.SetFxRate(v)
	return _u
}

// SetNillableFxRate sets the "fx_rate" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableFxRate(v *string) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetFxRate(*v)
	}
	return _u
}

// SetFormulaVersion sets the "formula_version" field.
func (_u *PoolSettlementUpdateOne) SetFormulaVersion(v string) *PoolSettlementUpdateOne {
	_u.mutation.SetFormulaVersion(v)
	return _u
}

// SetNillableFormulaVersion sets the "formula_version" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableFormulaVersion(v *string) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetFormulaVersion(*v)
	}
	return _u
}

// SetCostSnapshot sets the "cost_snapshot" field.
func (_u *PoolSettlementUpdateOne) SetCostSnapshot(v []map[string]interface{}) *PoolSettlementUpdateOne {
	_u.mutation.SetCostSnapshot(v)
	return _u
}

// AppendCostSnapshot appends value to the "cost_snapshot" field.
func (_u *PoolSettlementUpdateOne) AppendCostSnapshot(v []map[string]interface{}) *PoolSettlementUpdateOne {
	_u.mutation.AppendCostSnapshot(v)
	return _u
}

// SetGeneratedByUserID sets the "generated_by_user_id" field.
func (_u *PoolSettlementUpdateOne) SetGeneratedByUserID(v int64) *PoolSettlementUpdateOne {
	_u.mutation.ResetGeneratedByUserID()
	_u.mutation.SetGeneratedByUserID(v)
	return _u
}

// SetNillableGeneratedByUserID sets the "generated_by_user_id" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableGeneratedByUserID(v *int64) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetGeneratedByUserID(*v)
	}
	return _u
}

// AddGeneratedByUserID adds value to the "generated_by_user_id" field.
func (_u *PoolSettlementUpdateOne) AddGeneratedByUserID(v int64) *PoolSettlementUpdateOne {
	_u.mutation.AddGeneratedByUserID(v)
	return _u
}

// SetLockedByUserID sets the "locked_by_user_id" field.
func (_u *PoolSettlementUpdateOne) SetLockedByUserID(v int64) *PoolSettlementUpdateOne {
	_u.mutation.ResetLockedByUserID()
	_u.mutation.SetLockedByUserID(v)
	return _u
}

// SetNillableLockedByUserID sets the "locked_by_user_id" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableLockedByUserID(v *int64) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetLockedByUserID(*v)
	}
	return _u
}

// AddLockedByUserID adds value to the "locked_by_user_id" field.
func (_u *PoolSettlementUpdateOne) AddLockedByUserID(v int64) *PoolSettlementUpdateOne {
	_u.mutation.AddLockedByUserID(v)
	return _u
}

// ClearLockedByUserID clears the value of the "locked_by_user_id" field.
func (_u *PoolSettlementUpdateOne) ClearLockedByUserID() *PoolSettlementUpdateOne {
	_u.mutation.ClearLockedByUserID()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *PoolSettlementUpdateOne) SetLockedAt(v time.Time) *PoolSettlementUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *PoolSettlementUpdateOne) SetNillableLockedAt(v *time.Time) *PoolSettlementUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *PoolSettlementUpdateOne) ClearLockedAt() *PoolSettlementUpdateOne {
	_u.mutation.ClearLockedAt()
	return _u
}

// Mutation returns the PoolSettlementMutation object of the builder.
func (_u *PoolSettlementUpdateOne) Mutation() *PoolSettlementMutation {
	return _u.mutation
}

// Where appends a list predicates to the PoolSettlementUpdate builder.
func (_u *PoolSettlementUpdateOne) Where(ps ...predicate.PoolSettlement) *PoolSettlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PoolSettlementUpdateOne) Select(field string, fields ...string) *PoolSettlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PoolSettlement entity.
func (_u *PoolSettlementUpdateOne) Save(ctx context.Context) (*PoolSettlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PoolSettlementUpdateOne) SaveX(ctx context.Context) *PoolSettlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PoolSettlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PoolSettlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PoolSettlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := poolsettlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PoolSettlementUpdateOne) check() error {
	if v, ok := _u.mutation.PeriodType(); ok {
		if err := poolsettlement.PeriodTypeValidator(v); err != nil {
			return &ValidationError{Name: "period_type", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.period_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := poolsettlement.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := poolsettlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalUsageWeight(); ok {
		if err := poolsettlement.TotalUsageWeightValidator(v); err != nil {
			return &ValidationError{Name: "total_usage_weight", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.total_usage_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PricingCoverage(); ok {
		if err := poolsettlement.PricingCoverageValidator(v); err != nil {
			return &ValidationError{Name: "pricing_coverage", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.pricing_coverage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FxRate(); ok {
		if err := poolsettlement.FxRateValidator(v); err != nil {
			return &ValidationError{Name: "fx_rate", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.fx_rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FormulaVersion(); ok {
		if err := poolsettlement.FormulaVersionValidator(v); err != nil {
			return &ValidationError{Name: "formula_version", err: fmt.Errorf(`ent: validator failed for field "PoolSettlement.formula_version": %w`, err)}
		}
	}
	return nil
}

func (_u *PoolSettlementUpdateOne) sqlSave(ctx context.Context) (_node *PoolSettlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(poolsettlement.Table, poolsettlement.Columns, sqlgraph.NewFieldSpec(poolsettlement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PoolSettlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, poolsettlement.FieldID)
		for _, f := range fields {
			if !poolsettlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != poolsettlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(poolsettlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodType(); ok {
		_spec.SetField(poolsettlement.FieldPeriodType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(poolsettlement.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(poolsettlement.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(poolsettlement.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(poolsettlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodCostMinor(); ok {
		_spec.SetField(poolsettlement.FieldPeriodCostMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPeriodCostMinor(); ok {
		_spec.AddField(poolsettlement.FieldPeriodCostMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CarryInMinor(); ok {
		_spec.SetField(poolsettlement.FieldCarryInMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCarryInMinor(); ok {
		_spec.AddField(poolsettlement.FieldCarryInMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CarryOutMinor(); ok {
		_spec.SetField(poolsettlement.FieldCarryOutMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCarryOutMinor(); ok {
		_spec.AddField(poolsettlement.FieldCarryOutMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalCostMinor(); ok {
		_spec.SetField(poolsettlement.FieldTotalCostMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalCostMinor(); ok {
		_spec.AddField(poolsettlement.FieldTotalCostMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalUsageWeight(); ok {
		_spec.SetField(poolsettlement.FieldTotalUsageWeight, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricingCoverage(); ok {
		_spec.SetField(poolsettlement.FieldPricingCoverage, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnpricedUsageCount(); ok {
		_spec.SetField(poolsettlement.FieldUnpricedUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnpricedUsageCount(); ok {
		_spec.AddField(poolsettlement.FieldUnpricedUsageCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FxRate(); ok {
		_spec.SetField(poolsettlement.FieldFxRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.FormulaVersion(); ok {
		_spec.SetField(poolsettlement.FieldFormulaVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostSnapshot(); ok {
		_spec.SetField(poolsettlement.FieldCostSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCostSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, poolsettlement.FieldCostSnapshot, value)
		})
	}
	if value, ok := _u.mutation.GeneratedByUserID(); ok {
		_spec.SetField(poolsettlement.FieldGeneratedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGeneratedByUserID(); ok {
		_spec.AddField(poolsettlement.FieldGeneratedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LockedByUserID(); ok {
		_spec.SetField(poolsettlement.FieldLockedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLockedByUserID(); ok {
		_spec.AddField(poolsettlement.FieldLockedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.LockedByUserIDCleared() {
		_spec.ClearField(poolsettlement.FieldLockedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(poolsettlement.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(poolsettlement.FieldLockedAt, field.TypeTime)
	}
	_node = &PoolSettlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{poolsettlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
