// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/purchasesource"
)

// PurchaseSourceCreate is the builder for creating a PurchaseSource entity.
type PurchaseSourceCreate struct {
	config
	mutation *PurchaseSourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PurchaseSourceCreate) SetCreatedAt(v time.Time) *PurchaseSourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PurchaseSourceCreate) SetNillableCreatedAt(v *time.Time) *PurchaseSourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PurchaseSourceCreate) SetUpdatedAt(v time.Time) *PurchaseSourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PurchaseSourceCreate) SetNillableUpdatedAt(v *time.Time) *PurchaseSourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PurchaseSourceCreate) SetName(v string) *PurchaseSourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetWebsiteURL sets the "website_url" field.
func (_c *PurchaseSourceCreate) SetWebsiteURL(v string) *PurchaseSourceCreate {
	_c.mutation.SetWebsiteURL(v)
	return _c
}

// SetNillableWebsiteURL sets the "website_url" field if the given value is not nil.
func (_c *PurchaseSourceCreate) SetNillableWebsiteURL(v *string) *PurchaseSourceCreate {
	if v != nil {
		_c.SetWebsiteURL(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PurchaseSourceCreate) SetNotes(v string) *PurchaseSourceCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PurchaseSourceCreate) SetNillableNotes(v *string) *PurchaseSourceCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *PurchaseSourceCreate) SetActive(v bool) *PurchaseSourceCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *PurchaseSourceCreate) SetNillableActive(v *bool) *PurchaseSourceCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// Mutation returns the PurchaseSourceMutation object of the builder.
func (_c *PurchaseSourceCreate) Mutation() *PurchaseSourceMutation {
	return _c.mutation
}

// Save creates the PurchaseSource in the database.
func (_c *PurchaseSourceCreate) Save(ctx context.Context) (*PurchaseSource, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PurchaseSourceCreate) SaveX(ctx context.Context) *PurchaseSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PurchaseSourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PurchaseSourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PurchaseSourceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := purchasesource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := purchasesource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := purchasesource.DefaultActive
		_c.mutation.SetActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PurchaseSourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PurchaseSource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PurchaseSource.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PurchaseSource.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := purchasesource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PurchaseSource.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.WebsiteURL(); ok {
		if err := purchasesource.WebsiteURLValidator(v); err != nil {
			return &ValidationError{Name: "website_url", err: fmt.Errorf(`ent: validator failed for field "PurchaseSource.website_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "PurchaseSource.active"`)}
	}
	return nil
}

func (_c *PurchaseSourceCreate) sqlSave(ctx context.Context) (*PurchaseSource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PurchaseSourceCreate) createSpec() (*PurchaseSource, *sqlgraph.CreateSpec) {
	var (
		_node = &PurchaseSource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(purchasesource.Table, sqlgraph.NewFieldSpec(purchasesource.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(purchasesource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(purchasesource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(purchasesource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.WebsiteURL(); ok {
		_spec.SetField(purchasesource.FieldWebsiteURL, field.TypeString, value)
		_node.WebsiteURL = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(purchasesource.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(purchasesource.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PurchaseSource.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PurchaseSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PurchaseSourceCreate) OnConflict(opts ...sql.ConflictOption) *PurchaseSourceUpsertOne {
	_c.conflict = opts
	return &PurchaseSourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PurchaseSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PurchaseSourceCreate) OnConflictColumns(columns ...string) *PurchaseSourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PurchaseSourceUpsertOne{
		create: _c,
	}
}

type (
	// PurchaseSourceUpsertOne is the builder for "upsert"-ing
	//  one PurchaseSource node.
	PurchaseSourceUpsertOne struct {
		create *PurchaseSourceCreate
	}

	// PurchaseSourceUpsert is the "OnConflict" setter.
	PurchaseSourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PurchaseSourceUpsert) SetUpdatedAt(v time.Time) *PurchaseSourceUpsert {
	u.Set(purchasesource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PurchaseSourceUpsert) UpdateUpdatedAt() *PurchaseSourceUpsert {
	u.SetExcluded(purchasesource.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *PurchaseSourceUpsert) SetName(v string) *PurchaseSourceUpsert {
	u.Set(purchasesource.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PurchaseSourceUpsert) UpdateName() *PurchaseSourceUpsert {
	u.SetExcluded(purchasesource.FieldName)
	return u
}

// SetWebsiteURL sets the "website_url" field.
func (u *PurchaseSourceUpsert) SetWebsiteURL(v string) *PurchaseSourceUpsert {
	u.Set(purchasesource.FieldWebsiteURL, v)
	return u
}

// UpdateWebsiteURL sets the "website_url" field to the value that was provided on create.
func (u *PurchaseSourceUpsert) UpdateWebsiteURL() *PurchaseSourceUpsert {
	u.SetExcluded(purchasesource.FieldWebsiteURL)
	return u
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (u *PurchaseSourceUpsert) ClearWebsiteURL() *PurchaseSourceUpsert {
	u.SetNull(purchasesource.FieldWebsiteURL)
	return u
}

// SetNotes sets the "notes" field.
func (u *PurchaseSourceUpsert) SetNotes(v string) *PurchaseSourceUpsert {
	u.Set(purchasesource.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PurchaseSourceUpsert) UpdateNotes() *PurchaseSourceUpsert {
	u.SetExcluded(purchasesource.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *PurchaseSourceUpsert) ClearNotes() *PurchaseSourceUpsert {
	u.SetNull(purchasesource.FieldNotes)
	return u
}

// SetActive sets the "active" field.
func (u *PurchaseSourceUpsert) SetActive(v bool) *PurchaseSourceUpsert {
	u.Set(purchasesource.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *PurchaseSourceUpsert) UpdateActive() *PurchaseSourceUpsert {
	u.SetExcluded(purchasesource.FieldActive)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PurchaseSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PurchaseSourceUpsertOne) UpdateNewValues() *PurchaseSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(purchasesource.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PurchaseSource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PurchaseSourceUpsertOne) Ignore() *PurchaseSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PurchaseSourceUpsertOne) DoNothing() *PurchaseSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PurchaseSourceCreate.OnConflict
// documentation for more info.
func (u *PurchaseSourceUpsertOne) Update(set func(*PurchaseSourceUpsert)) *PurchaseSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PurchaseSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PurchaseSourceUpsertOne) SetUpdatedAt(v time.Time) *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PurchaseSourceUpsertOne) UpdateUpdatedAt() *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *PurchaseSourceUpsertOne) SetName(v string) *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PurchaseSourceUpsertOne) UpdateName() *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateName()
	})
}

// SetWebsiteURL sets the "website_url" field.
func (u *PurchaseSourceUpsertOne) SetWebsiteURL(v string) *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetWebsiteURL(v)
	})
}

// UpdateWebsiteURL sets the "website_url" field to the value that was provided on create.
func (u *PurchaseSourceUpsertOne) UpdateWebsiteURL() *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateWebsiteURL()
	})
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (u *PurchaseSourceUpsertOne) ClearWebsiteURL() *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.ClearWebsiteURL()
	})
}

// SetNotes sets the "notes" field.
func (u *PurchaseSourceUpsertOne) SetNotes(v string) *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PurchaseSourceUpsertOne) UpdateNotes() *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PurchaseSourceUpsertOne) ClearNotes() *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.ClearNotes()
	})
}

// SetActive sets the "active" field.
func (u *PurchaseSourceUpsertOne) SetActive(v bool) *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *PurchaseSourceUpsertOne) UpdateActive() *PurchaseSourceUpsertOne {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateActive()
	})
}

// Exec executes the query.
func (u *PurchaseSourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PurchaseSourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PurchaseSourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PurchaseSourceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PurchaseSourceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PurchaseSourceCreateBulk is the builder for creating many PurchaseSource entities in bulk.
type PurchaseSourceCreateBulk struct {
	config
	err      error
	builders []*PurchaseSourceCreate
	conflict []sql.ConflictOption
}

// Save creates the PurchaseSource entities in the database.
func (_c *PurchaseSourceCreateBulk) Save(ctx context.Context) ([]*PurchaseSource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PurchaseSource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PurchaseSourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PurchaseSourceCreateBulk) SaveX(ctx context.Context) []*PurchaseSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PurchaseSourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PurchaseSourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PurchaseSource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PurchaseSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PurchaseSourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *PurchaseSourceUpsertBulk {
	_c.conflict = opts
	return &PurchaseSourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PurchaseSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PurchaseSourceCreateBulk) OnConflictColumns(columns ...string) *PurchaseSourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PurchaseSourceUpsertBulk{
		create: _c,
	}
}

// PurchaseSourceUpsertBulk is the builder for "upsert"-ing
// a bulk of PurchaseSource nodes.
type PurchaseSourceUpsertBulk struct {
	create *PurchaseSourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PurchaseSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PurchaseSourceUpsertBulk) UpdateNewValues() *PurchaseSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(purchasesource.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PurchaseSource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PurchaseSourceUpsertBulk) Ignore() *PurchaseSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PurchaseSourceUpsertBulk) DoNothing() *PurchaseSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PurchaseSourceCreateBulk.OnConflict
// documentation for more info.
func (u *PurchaseSourceUpsertBulk) Update(set func(*PurchaseSourceUpsert)) *PurchaseSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PurchaseSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PurchaseSourceUpsertBulk) SetUpdatedAt(v time.Time) *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PurchaseSourceUpsertBulk) UpdateUpdatedAt() *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *PurchaseSourceUpsertBulk) SetName(v string) *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PurchaseSourceUpsertBulk) UpdateName() *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateName()
	})
}

// SetWebsiteURL sets the "website_url" field.
func (u *PurchaseSourceUpsertBulk) SetWebsiteURL(v string) *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetWebsiteURL(v)
	})
}

// UpdateWebsiteURL sets the "website_url" field to the value that was provided on create.
func (u *PurchaseSourceUpsertBulk) UpdateWebsiteURL() *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateWebsiteURL()
	})
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (u *PurchaseSourceUpsertBulk) ClearWebsiteURL() *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.ClearWebsiteURL()
	})
}

// SetNotes sets the "notes" field.
func (u *PurchaseSourceUpsertBulk) SetNotes(v string) *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PurchaseSourceUpsertBulk) UpdateNotes() *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PurchaseSourceUpsertBulk) ClearNotes() *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.ClearNotes()
	})
}

// SetActive sets the "active" field.
func (u *PurchaseSourceUpsertBulk) SetActive(v bool) *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *PurchaseSourceUpsertBulk) UpdateActive() *PurchaseSourceUpsertBulk {
	return u.Update(func(s *PurchaseSourceUpsert) {
		s.UpdateActive()
	})
}

// Exec executes the query.
func (u *PurchaseSourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PurchaseSourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PurchaseSourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PurchaseSourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
