// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/purchasesource"
)

// PurchaseSourceUpdate is the builder for updating PurchaseSource entities.
type PurchaseSourceUpdate struct {
	config
	hooks    []Hook
	mutation *PurchaseSourceMutation
}

// Where appends a list predicates to the PurchaseSourceUpdate builder.
func (_u *PurchaseSourceUpdate) Where(ps ...predicate.PurchaseSource) *PurchaseSourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PurchaseSourceUpdate) SetUpdatedAt(v time.Time) *PurchaseSourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PurchaseSourceUpdate) SetName(v string) *PurchaseSourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PurchaseSourceUpdate) SetNillableName(v *string) *PurchaseSourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWebsiteURL sets the "website_url" field.
func (_u *PurchaseSourceUpdate) SetWebsiteURL(v string) *PurchaseSourceUpdate {
	_u.mutation.SetWebsiteURL(v)
	return _u
}

// SetNillableWebsiteURL sets the "website_url" field if the given value is not nil.
func (_u *PurchaseSourceUpdate) SetNillableWebsiteURL(v *string) *PurchaseSourceUpdate {
	if v != nil {
		_u.SetWebsiteURL(*v)
	}
	return _u
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (_u *PurchaseSourceUpdate) ClearWebsiteURL() *PurchaseSourceUpdate {
	_u.mutation.ClearWebsiteURL()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PurchaseSourceUpdate) SetNotes(v string) *PurchaseSourceUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PurchaseSourceUpdate) SetNillableNotes(v *string) *PurchaseSourceUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PurchaseSourceUpdate) ClearNotes() *PurchaseSourceUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetActive sets the "active" field.
func (_u *PurchaseSourceUpdate) SetActive(v bool) *PurchaseSourceUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *PurchaseSourceUpdate) SetNillableActive(v *bool) *PurchaseSourceUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the PurchaseSourceMutation object of the builder.
func (_u *PurchaseSourceUpdate) Mutation() *PurchaseSourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PurchaseSourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PurchaseSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PurchaseSourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PurchaseSourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PurchaseSourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := purchasesource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PurchaseSourceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := purchasesource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PurchaseSource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebsiteURL(); ok {
		if err := purchasesource.WebsiteURLValidator(v); err != nil {
			return &ValidationError{Name: "website_url", err: fmt.Errorf(`ent: validator failed for field "PurchaseSource.website_url": %w`, err)}
		}
	}
	return nil
}

func (_u *PurchaseSourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(purchasesource.Table, purchasesource.Columns, sqlgraph.NewFieldSpec(purchasesource.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(purchasesource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(purchasesource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebsiteURL(); ok {
		_spec.SetField(purchasesource.FieldWebsiteURL, field.TypeString, value)
	}
	if _u.mutation.WebsiteURLCleared() {
		_spec.ClearField(purchasesource.FieldWebsiteURL, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(purchasesource.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(purchasesource.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(purchasesource.FieldActive, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{purchasesource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PurchaseSourceUpdateOne is the builder for updating a single PurchaseSource entity.
type PurchaseSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PurchaseSourceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PurchaseSourceUpdateOne) SetUpdatedAt(v time.Time) *PurchaseSourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PurchaseSourceUpdateOne) SetName(v string) *PurchaseSourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PurchaseSourceUpdateOne) SetNillableName(v *string) *PurchaseSourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWebsiteURL sets the "website_url" field.
func (_u *PurchaseSourceUpdateOne) SetWebsiteURL(v string) *PurchaseSourceUpdateOne {
	_u.mutation.SetWebsiteURL(v)
	return _u
}

// SetNillableWebsiteURL sets the "website_url" field if the given value is not nil.
func (_u *PurchaseSourceUpdateOne) SetNillableWebsiteURL(v *string) *PurchaseSourceUpdateOne {
	if v != nil {
		_u.SetWebsiteURL(*v)
	}
	return _u
}

// ClearWebsiteURL clears the value of the "website_url" field.
func (_u *PurchaseSourceUpdateOne) ClearWebsiteURL() *PurchaseSourceUpdateOne {
	_u.mutation.ClearWebsiteURL()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PurchaseSourceUpdateOne) SetNotes(v string) *PurchaseSourceUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PurchaseSourceUpdateOne) SetNillableNotes(v *string) *PurchaseSourceUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PurchaseSourceUpdateOne) ClearNotes() *PurchaseSourceUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetActive sets the "active" field.
func (_u *PurchaseSourceUpdateOne) SetActive(v bool) *PurchaseSourceUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *PurchaseSourceUpdateOne) SetNillableActive(v *bool) *PurchaseSourceUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the PurchaseSourceMutation object of the builder.
func (_u *PurchaseSourceUpdateOne) Mutation() *PurchaseSourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the PurchaseSourceUpdate builder.
func (_u *PurchaseSourceUpdateOne) Where(ps ...predicate.PurchaseSource) *PurchaseSourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PurchaseSourceUpdateOne) Select(field string, fields ...string) *PurchaseSourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PurchaseSource entity.
func (_u *PurchaseSourceUpdateOne) Save(ctx context.Context) (*PurchaseSource, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PurchaseSourceUpdateOne) SaveX(ctx context.Context) *PurchaseSource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PurchaseSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PurchaseSourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PurchaseSourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := purchasesource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PurchaseSourceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := purchasesource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PurchaseSource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebsiteURL(); ok {
		if err := purchasesource.WebsiteURLValidator(v); err != nil {
			return &ValidationError{Name: "website_url", err: fmt.Errorf(`ent: validator failed for field "PurchaseSource.website_url": %w`, err)}
		}
	}
	return nil
}

func (_u *PurchaseSourceUpdateOne) sqlSave(ctx context.Context) (_node *PurchaseSource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(purchasesource.Table, purchasesource.Columns, sqlgraph.NewFieldSpec(purchasesource.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PurchaseSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, purchasesource.FieldID)
		for _, f := range fields {
			if !purchasesource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != purchasesource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(purchasesource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(purchasesource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebsiteURL(); ok {
		_spec.SetField(purchasesource.FieldWebsiteURL, field.TypeString, value)
	}
	if _u.mutation.WebsiteURLCleared() {
		_spec.ClearField(purchasesource.FieldWebsiteURL, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(purchasesource.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(purchasesource.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(purchasesource.FieldActive, field.TypeBool, value)
	}
	_node = &PurchaseSource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{purchasesource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
