// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/valuationfxrate"
)

// ValuationFXRate is the model entity for the ValuationFXRate schema.
type ValuationFXRate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// BaseCurrency holds the value of the "base_currency" field.
	BaseCurrency string `json:"base_currency,omitempty"`
	// QuoteCurrency holds the value of the "quote_currency" field.
	QuoteCurrency string `json:"quote_currency,omitempty"`
	// Rate holds the value of the "rate" field.
	Rate string `json:"rate,omitempty"`
	// EffectiveFrom holds the value of the "effective_from" field.
	EffectiveFrom time.Time `json:"effective_from,omitempty"`
	// Source holds the value of the "source" field.
	Source *string `json:"source,omitempty"`
	// CreatedByUserID holds the value of the "created_by_user_id" field.
	CreatedByUserID int64 `json:"created_by_user_id,omitempty"`
	selectValues    sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ValuationFXRate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case valuationfxrate.FieldID, valuationfxrate.FieldCreatedByUserID:
			values[i] = new(sql.NullInt64)
		case valuationfxrate.FieldBaseCurrency, valuationfxrate.FieldQuoteCurrency, valuationfxrate.FieldRate, valuationfxrate.FieldSource:
			values[i] = new(sql.NullString)
		case valuationfxrate.FieldCreatedAt, valuationfxrate.FieldUpdatedAt, valuationfxrate.FieldEffectiveFrom:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ValuationFXRate fields.
func (_m *ValuationFXRate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case valuationfxrate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case valuationfxrate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case valuationfxrate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case valuationfxrate.FieldBaseCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_currency", values[i])
			} else if value.Valid {
				_m.BaseCurrency = value.String
			}
		case valuationfxrate.FieldQuoteCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quote_currency", values[i])
			} else if value.Valid {
				_m.QuoteCurrency = value.String
			}
		case valuationfxrate.FieldRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				_m.Rate = value.String
			}
		case valuationfxrate.FieldEffectiveFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_from", values[i])
			} else if value.Valid {
				_m.EffectiveFrom = value.Time
			}
		case valuationfxrate.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = new(string)
				*_m.Source = value.String
			}
		case valuationfxrate.FieldCreatedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_user_id", values[i])
			} else if value.Valid {
				_m.CreatedByUserID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ValuationFXRate.
// This includes values selected through modifiers, order, etc.
func (_m *ValuationFXRate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ValuationFXRate.
// Note that you need to call ValuationFXRate.Unwrap() before calling this method if this ValuationFXRate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ValuationFXRate) Update() *ValuationFXRateUpdateOne {
	return NewValuationFXRateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ValuationFXRate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ValuationFXRate) Unwrap() *ValuationFXRate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ValuationFXRate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ValuationFXRate) String() string {
	var builder strings.Builder
	builder.WriteString("ValuationFXRate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("base_currency=")
	builder.WriteString(_m.BaseCurrency)
	builder.WriteString(", ")
	builder.WriteString("quote_currency=")
	builder.WriteString(_m.QuoteCurrency)
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(_m.Rate)
	builder.WriteString(", ")
	builder.WriteString("effective_from=")
	builder.WriteString(_m.EffectiveFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Source; v != nil {
		builder.WriteString("source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_by_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedByUserID))
	builder.WriteByte(')')
	return builder.String()
}

// ValuationFXRates is a parsable slice of ValuationFXRate.
type ValuationFXRates []*ValuationFXRate
