// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/valuationfxrate"
)

// ValuationFXRateUpdate is the builder for updating ValuationFXRate entities.
type ValuationFXRateUpdate struct {
	config
	hooks    []Hook
	mutation *ValuationFXRateMutation
}

// Where appends a list predicates to the ValuationFXRateUpdate builder.
func (_u *ValuationFXRateUpdate) Where(ps ...predicate.ValuationFXRate) *ValuationFXRateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ValuationFXRateUpdate) SetUpdatedAt(v time.Time) *ValuationFXRateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBaseCurrency sets the "base_currency" field.
func (_u *ValuationFXRateUpdate) SetBaseCurrency(v string) *ValuationFXRateUpdate {
	_u.mutation.SetBaseCurrency(v)
	return _u
}

// SetNillableBaseCurrency sets the "base_currency" field if the given value is not nil.
func (_u *ValuationFXRateUpdate) SetNillableBaseCurrency(v *string) *ValuationFXRateUpdate {
	if v != nil {
		_u.SetBaseCurrency(*v)
	}
	return _u
}

// SetQuoteCurrency sets the "quote_currency" field.
func (_u *ValuationFXRateUpdate) SetQuoteCurrency(v string) *ValuationFXRateUpdate {
	_u.mutation.SetQuoteCurrency(v)
	return _u
}

// SetNillableQuoteCurrency sets the "quote_currency" field if the given value is not nil.
func (_u *ValuationFXRateUpdate) SetNillableQuoteCurrency(v *string) *ValuationFXRateUpdate {
	if v != nil {
		_u.SetQuoteCurrency(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *ValuationFXRateUpdate) SetRate(v string) *ValuationFXRateUpdate {
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *ValuationFXRateUpdate) SetNillableRate(v *string) *ValuationFXRateUpdate {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *ValuationFXRateUpdate) SetEffectiveFrom(v time.Time) *ValuationFXRateUpdate {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *ValuationFXRateUpdate) SetNillableEffectiveFrom(v *time.Time) *ValuationFXRateUpdate {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ValuationFXRateUpdate) SetSource(v string) *ValuationFXRateUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ValuationFXRateUpdate) SetNillableSource(v *string) *ValuationFXRateUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *ValuationFXRateUpdate) ClearSource() *ValuationFXRateUpdate {
	_u.mutation.ClearSource()
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *ValuationFXRateUpdate) SetCreatedByUserID(v int64) *ValuationFXRateUpdate {
	_u.mutation.ResetCreatedByUserID()
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *ValuationFXRateUpdate) SetNillableCreatedByUserID(v *int64) *ValuationFXRateUpdate {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// AddCreatedByUserID adds value to the "created_by_user_id" field.
func (_u *ValuationFXRateUpdate) AddCreatedByUserID(v int64) *ValuationFXRateUpdate {
	_u.mutation.AddCreatedByUserID(v)
	return _u
}

// Mutation returns the ValuationFXRateMutation object of the builder.
func (_u *ValuationFXRateUpdate) Mutation() *ValuationFXRateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ValuationFXRateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ValuationFXRateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ValuationFXRateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ValuationFXRateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ValuationFXRateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := valuationfxrate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ValuationFXRateUpdate) check() error {
	if v, ok := _u.mutation.BaseCurrency(); ok {
		if err := valuationfxrate.BaseCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "base_currency", err: fmt.Errorf(`ent: validator failed for field "ValuationFXRate.base_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuoteCurrency(); ok {
		if err := valuationfxrate.QuoteCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "quote_currency", err: fmt.Errorf(`ent: validator failed for field "ValuationFXRate.quote_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rate(); ok {
		if err := valuationfxrate.RateValidator(v); err != nil {
			return &ValidationError{Name: "rate", err: fmt.Errorf(`ent: validator failed for field "ValuationFXRate.rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := valuationfxrate.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ValuationFXRate.source": %w`, err)}
		}
	}
	return nil
}

func (_u *ValuationFXRateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(valuationfxrate.Table, valuationfxrate.Columns, sqlgraph.NewFieldSpec(valuationfxrate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(valuationfxrate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BaseCurrency(); ok {
		_spec.SetField(valuationfxrate.FieldBaseCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuoteCurrency(); ok {
		_spec.SetField(valuationfxrate.FieldQuoteCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(valuationfxrate.FieldRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(valuationfxrate.FieldEffectiveFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(valuationfxrate.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(valuationfxrate.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedByUserID(); ok {
		_spec.SetField(valuationfxrate.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByUserID(); ok {
		_spec.AddField(valuationfxrate.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{valuationfxrate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ValuationFXRateUpdateOne is the builder for updating a single ValuationFXRate entity.
type ValuationFXRateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ValuationFXRateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ValuationFXRateUpdateOne) SetUpdatedAt(v time.Time) *ValuationFXRateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBaseCurrency sets the "base_currency" field.
func (_u *ValuationFXRateUpdateOne) SetBaseCurrency(v string) *ValuationFXRateUpdateOne {
	_u.mutation.SetBaseCurrency(v)
	return _u
}

// SetNillableBaseCurrency sets the "base_currency" field if the given value is not nil.
func (_u *ValuationFXRateUpdateOne) SetNillableBaseCurrency(v *string) *ValuationFXRateUpdateOne {
	if v != nil {
		_u.SetBaseCurrency(*v)
	}
	return _u
}

// SetQuoteCurrency sets the "quote_currency" field.
func (_u *ValuationFXRateUpdateOne) SetQuoteCurrency(v string) *ValuationFXRateUpdateOne {
	_u.mutation.SetQuoteCurrency(v)
	return _u
}

// SetNillableQuoteCurrency sets the "quote_currency" field if the given value is not nil.
func (_u *ValuationFXRateUpdateOne) SetNillableQuoteCurrency(v *string) *ValuationFXRateUpdateOne {
	if v != nil {
		_u.SetQuoteCurrency(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *ValuationFXRateUpdateOne) SetRate(v string) *ValuationFXRateUpdateOne {
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *ValuationFXRateUpdateOne) SetNillableRate(v *string) *ValuationFXRateUpdateOne {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *ValuationFXRateUpdateOne) SetEffectiveFrom(v time.Time) *ValuationFXRateUpdateOne {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *ValuationFXRateUpdateOne) SetNillableEffectiveFrom(v *time.Time) *ValuationFXRateUpdateOne {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ValuationFXRateUpdateOne) SetSource(v string) *ValuationFXRateUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ValuationFXRateUpdateOne) SetNillableSource(v *string) *ValuationFXRateUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *ValuationFXRateUpdateOne) ClearSource() *ValuationFXRateUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *ValuationFXRateUpdateOne) SetCreatedByUserID(v int64) *ValuationFXRateUpdateOne {
	_u.mutation.ResetCreatedByUserID()
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *ValuationFXRateUpdateOne) SetNillableCreatedByUserID(v *int64) *ValuationFXRateUpdateOne {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// AddCreatedByUserID adds value to the "created_by_user_id" field.
func (_u *ValuationFXRateUpdateOne) AddCreatedByUserID(v int64) *ValuationFXRateUpdateOne {
	_u.mutation.AddCreatedByUserID(v)
	return _u
}

// Mutation returns the ValuationFXRateMutation object of the builder.
func (_u *ValuationFXRateUpdateOne) Mutation() *ValuationFXRateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ValuationFXRateUpdate builder.
func (_u *ValuationFXRateUpdateOne) Where(ps ...predicate.ValuationFXRate) *ValuationFXRateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ValuationFXRateUpdateOne) Select(field string, fields ...string) *ValuationFXRateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ValuationFXRate entity.
func (_u *ValuationFXRateUpdateOne) Save(ctx context.Context) (*ValuationFXRate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ValuationFXRateUpdateOne) SaveX(ctx context.Context) *ValuationFXRate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ValuationFXRateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ValuationFXRateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ValuationFXRateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := valuationfxrate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ValuationFXRateUpdateOne) check() error {
	if v, ok := _u.mutation.BaseCurrency(); ok {
		if err := valuationfxrate.BaseCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "base_currency", err: fmt.Errorf(`ent: validator failed for field "ValuationFXRate.base_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuoteCurrency(); ok {
		if err := valuationfxrate.QuoteCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "quote_currency", err: fmt.Errorf(`ent: validator failed for field "ValuationFXRate.quote_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rate(); ok {
		if err := valuationfxrate.RateValidator(v); err != nil {
			return &ValidationError{Name: "rate", err: fmt.Errorf(`ent: validator failed for field "ValuationFXRate.rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := valuationfxrate.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ValuationFXRate.source": %w`, err)}
		}
	}
	return nil
}

func (_u *ValuationFXRateUpdateOne) sqlSave(ctx context.Context) (_node *ValuationFXRate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(valuationfxrate.Table, valuationfxrate.Columns, sqlgraph.NewFieldSpec(valuationfxrate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ValuationFXRate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, valuationfxrate.FieldID)
		for _, f := range fields {
			if !valuationfxrate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != valuationfxrate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(valuationfxrate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BaseCurrency(); ok {
		_spec.SetField(valuationfxrate.FieldBaseCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuoteCurrency(); ok {
		_spec.SetField(valuationfxrate.FieldQuoteCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(valuationfxrate.FieldRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(valuationfxrate.FieldEffectiveFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(valuationfxrate.FieldSource, field.TypeString, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(valuationfxrate.FieldSource, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedByUserID(); ok {
		_spec.SetField(valuationfxrate.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByUserID(); ok {
		_spec.AddField(valuationfxrate.FieldCreatedByUserID, field.TypeInt64, value)
	}
	_node = &ValuationFXRate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{valuationfxrate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
