// Code generated by ent, DO NOT EDIT.

package poolsettlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// PeriodType applies equality check predicate on the "period_type" field. It's identical to PeriodTypeEQ.
func PeriodType(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPeriodType, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPeriodEnd, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldTimezone, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldStatus, v))
}

// PeriodCostMinor applies equality check predicate on the "period_cost_minor" field. It's identical to PeriodCostMinorEQ.
func PeriodCostMinor(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPeriodCostMinor, v))
}

// CarryInMinor applies equality check predicate on the "carry_in_minor" field. It's identical to CarryInMinorEQ.
func CarryInMinor(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldCarryInMinor, v))
}

// CarryOutMinor applies equality check predicate on the "carry_out_minor" field. It's identical to CarryOutMinorEQ.
func CarryOutMinor(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldCarryOutMinor, v))
}

// TotalCostMinor applies equality check predicate on the "total_cost_minor" field. It's identical to TotalCostMinorEQ.
func TotalCostMinor(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldTotalCostMinor, v))
}

// TotalUsageWeight applies equality check predicate on the "total_usage_weight" field. It's identical to TotalUsageWeightEQ.
func TotalUsageWeight(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldTotalUsageWeight, v))
}

// PricingCoverage applies equality check predicate on the "pricing_coverage" field. It's identical to PricingCoverageEQ.
func PricingCoverage(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPricingCoverage, v))
}

// UnpricedUsageCount applies equality check predicate on the "unpriced_usage_count" field. It's identical to UnpricedUsageCountEQ.
func UnpricedUsageCount(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldUnpricedUsageCount, v))
}

// FxRate applies equality check predicate on the "fx_rate" field. It's identical to FxRateEQ.
func FxRate(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldFxRate, v))
}

// FormulaVersion applies equality check predicate on the "formula_version" field. It's identical to FormulaVersionEQ.
func FormulaVersion(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldFormulaVersion, v))
}

// GeneratedByUserID applies equality check predicate on the "generated_by_user_id" field. It's identical to GeneratedByUserIDEQ.
func GeneratedByUserID(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldGeneratedByUserID, v))
}

// LockedByUserID applies equality check predicate on the "locked_by_user_id" field. It's identical to LockedByUserIDEQ.
func LockedByUserID(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldLockedByUserID, v))
}

// LockedAt applies equality check predicate on the "locked_at" field. It's identical to LockedAtEQ.
func LockedAt(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldLockedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// PeriodTypeEQ applies the EQ predicate on the "period_type" field.
func PeriodTypeEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPeriodType, v))
}

// PeriodTypeNEQ applies the NEQ predicate on the "period_type" field.
func PeriodTypeNEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldPeriodType, v))
}

// PeriodTypeIn applies the In predicate on the "period_type" field.
func PeriodTypeIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldPeriodType, vs...))
}

// PeriodTypeNotIn applies the NotIn predicate on the "period_type" field.
func PeriodTypeNotIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldPeriodType, vs...))
}

// PeriodTypeGT applies the GT predicate on the "period_type" field.
func PeriodTypeGT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldPeriodType, v))
}

// PeriodTypeGTE applies the GTE predicate on the "period_type" field.
func PeriodTypeGTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldPeriodType, v))
}

// PeriodTypeLT applies the LT predicate on the "period_type" field.
func PeriodTypeLT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldPeriodType, v))
}

// PeriodTypeLTE applies the LTE predicate on the "period_type" field.
func PeriodTypeLTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldPeriodType, v))
}

// PeriodTypeContains applies the Contains predicate on the "period_type" field.
func PeriodTypeContains(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContains(FieldPeriodType, v))
}

// PeriodTypeHasPrefix applies the HasPrefix predicate on the "period_type" field.
func PeriodTypeHasPrefix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasPrefix(FieldPeriodType, v))
}

// PeriodTypeHasSuffix applies the HasSuffix predicate on the "period_type" field.
func PeriodTypeHasSuffix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasSuffix(FieldPeriodType, v))
}

// PeriodTypeEqualFold applies the EqualFold predicate on the "period_type" field.
func PeriodTypeEqualFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEqualFold(FieldPeriodType, v))
}

// PeriodTypeContainsFold applies the ContainsFold predicate on the "period_type" field.
func PeriodTypeContainsFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContainsFold(FieldPeriodType, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldPeriodEnd, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContainsFold(FieldTimezone, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContainsFold(FieldStatus, v))
}

// PeriodCostMinorEQ applies the EQ predicate on the "period_cost_minor" field.
func PeriodCostMinorEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPeriodCostMinor, v))
}

// PeriodCostMinorNEQ applies the NEQ predicate on the "period_cost_minor" field.
func PeriodCostMinorNEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldPeriodCostMinor, v))
}

// PeriodCostMinorIn applies the In predicate on the "period_cost_minor" field.
func PeriodCostMinorIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldPeriodCostMinor, vs...))
}

// PeriodCostMinorNotIn applies the NotIn predicate on the "period_cost_minor" field.
func PeriodCostMinorNotIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldPeriodCostMinor, vs...))
}

// PeriodCostMinorGT applies the GT predicate on the "period_cost_minor" field.
func PeriodCostMinorGT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldPeriodCostMinor, v))
}

// PeriodCostMinorGTE applies the GTE predicate on the "period_cost_minor" field.
func PeriodCostMinorGTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldPeriodCostMinor, v))
}

// PeriodCostMinorLT applies the LT predicate on the "period_cost_minor" field.
func PeriodCostMinorLT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldPeriodCostMinor, v))
}

// PeriodCostMinorLTE applies the LTE predicate on the "period_cost_minor" field.
func PeriodCostMinorLTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldPeriodCostMinor, v))
}

// CarryInMinorEQ applies the EQ predicate on the "carry_in_minor" field.
func CarryInMinorEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldCarryInMinor, v))
}

// CarryInMinorNEQ applies the NEQ predicate on the "carry_in_minor" field.
func CarryInMinorNEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldCarryInMinor, v))
}

// CarryInMinorIn applies the In predicate on the "carry_in_minor" field.
func CarryInMinorIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldCarryInMinor, vs...))
}

// CarryInMinorNotIn applies the NotIn predicate on the "carry_in_minor" field.
func CarryInMinorNotIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldCarryInMinor, vs...))
}

// CarryInMinorGT applies the GT predicate on the "carry_in_minor" field.
func CarryInMinorGT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldCarryInMinor, v))
}

// CarryInMinorGTE applies the GTE predicate on the "carry_in_minor" field.
func CarryInMinorGTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldCarryInMinor, v))
}

// CarryInMinorLT applies the LT predicate on the "carry_in_minor" field.
func CarryInMinorLT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldCarryInMinor, v))
}

// CarryInMinorLTE applies the LTE predicate on the "carry_in_minor" field.
func CarryInMinorLTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldCarryInMinor, v))
}

// CarryOutMinorEQ applies the EQ predicate on the "carry_out_minor" field.
func CarryOutMinorEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldCarryOutMinor, v))
}

// CarryOutMinorNEQ applies the NEQ predicate on the "carry_out_minor" field.
func CarryOutMinorNEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldCarryOutMinor, v))
}

// CarryOutMinorIn applies the In predicate on the "carry_out_minor" field.
func CarryOutMinorIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldCarryOutMinor, vs...))
}

// CarryOutMinorNotIn applies the NotIn predicate on the "carry_out_minor" field.
func CarryOutMinorNotIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldCarryOutMinor, vs...))
}

// CarryOutMinorGT applies the GT predicate on the "carry_out_minor" field.
func CarryOutMinorGT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldCarryOutMinor, v))
}

// CarryOutMinorGTE applies the GTE predicate on the "carry_out_minor" field.
func CarryOutMinorGTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldCarryOutMinor, v))
}

// CarryOutMinorLT applies the LT predicate on the "carry_out_minor" field.
func CarryOutMinorLT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldCarryOutMinor, v))
}

// CarryOutMinorLTE applies the LTE predicate on the "carry_out_minor" field.
func CarryOutMinorLTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldCarryOutMinor, v))
}

// TotalCostMinorEQ applies the EQ predicate on the "total_cost_minor" field.
func TotalCostMinorEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldTotalCostMinor, v))
}

// TotalCostMinorNEQ applies the NEQ predicate on the "total_cost_minor" field.
func TotalCostMinorNEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldTotalCostMinor, v))
}

// TotalCostMinorIn applies the In predicate on the "total_cost_minor" field.
func TotalCostMinorIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldTotalCostMinor, vs...))
}

// TotalCostMinorNotIn applies the NotIn predicate on the "total_cost_minor" field.
func TotalCostMinorNotIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldTotalCostMinor, vs...))
}

// TotalCostMinorGT applies the GT predicate on the "total_cost_minor" field.
func TotalCostMinorGT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldTotalCostMinor, v))
}

// TotalCostMinorGTE applies the GTE predicate on the "total_cost_minor" field.
func TotalCostMinorGTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldTotalCostMinor, v))
}

// TotalCostMinorLT applies the LT predicate on the "total_cost_minor" field.
func TotalCostMinorLT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldTotalCostMinor, v))
}

// TotalCostMinorLTE applies the LTE predicate on the "total_cost_minor" field.
func TotalCostMinorLTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldTotalCostMinor, v))
}

// TotalUsageWeightEQ applies the EQ predicate on the "total_usage_weight" field.
func TotalUsageWeightEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldTotalUsageWeight, v))
}

// TotalUsageWeightNEQ applies the NEQ predicate on the "total_usage_weight" field.
func TotalUsageWeightNEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldTotalUsageWeight, v))
}

// TotalUsageWeightIn applies the In predicate on the "total_usage_weight" field.
func TotalUsageWeightIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldTotalUsageWeight, vs...))
}

// TotalUsageWeightNotIn applies the NotIn predicate on the "total_usage_weight" field.
func TotalUsageWeightNotIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldTotalUsageWeight, vs...))
}

// TotalUsageWeightGT applies the GT predicate on the "total_usage_weight" field.
func TotalUsageWeightGT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldTotalUsageWeight, v))
}

// TotalUsageWeightGTE applies the GTE predicate on the "total_usage_weight" field.
func TotalUsageWeightGTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldTotalUsageWeight, v))
}

// TotalUsageWeightLT applies the LT predicate on the "total_usage_weight" field.
func TotalUsageWeightLT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldTotalUsageWeight, v))
}

// TotalUsageWeightLTE applies the LTE predicate on the "total_usage_weight" field.
func TotalUsageWeightLTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldTotalUsageWeight, v))
}

// TotalUsageWeightContains applies the Contains predicate on the "total_usage_weight" field.
func TotalUsageWeightContains(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContains(FieldTotalUsageWeight, v))
}

// TotalUsageWeightHasPrefix applies the HasPrefix predicate on the "total_usage_weight" field.
func TotalUsageWeightHasPrefix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasPrefix(FieldTotalUsageWeight, v))
}

// TotalUsageWeightHasSuffix applies the HasSuffix predicate on the "total_usage_weight" field.
func TotalUsageWeightHasSuffix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasSuffix(FieldTotalUsageWeight, v))
}

// TotalUsageWeightEqualFold applies the EqualFold predicate on the "total_usage_weight" field.
func TotalUsageWeightEqualFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEqualFold(FieldTotalUsageWeight, v))
}

// TotalUsageWeightContainsFold applies the ContainsFold predicate on the "total_usage_weight" field.
func TotalUsageWeightContainsFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContainsFold(FieldTotalUsageWeight, v))
}

// PricingCoverageEQ applies the EQ predicate on the "pricing_coverage" field.
func PricingCoverageEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldPricingCoverage, v))
}

// PricingCoverageNEQ applies the NEQ predicate on the "pricing_coverage" field.
func PricingCoverageNEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldPricingCoverage, v))
}

// PricingCoverageIn applies the In predicate on the "pricing_coverage" field.
func PricingCoverageIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldPricingCoverage, vs...))
}

// PricingCoverageNotIn applies the NotIn predicate on the "pricing_coverage" field.
func PricingCoverageNotIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldPricingCoverage, vs...))
}

// PricingCoverageGT applies the GT predicate on the "pricing_coverage" field.
func PricingCoverageGT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldPricingCoverage, v))
}

// PricingCoverageGTE applies the GTE predicate on the "pricing_coverage" field.
func PricingCoverageGTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldPricingCoverage, v))
}

// PricingCoverageLT applies the LT predicate on the "pricing_coverage" field.
func PricingCoverageLT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldPricingCoverage, v))
}

// PricingCoverageLTE applies the LTE predicate on the "pricing_coverage" field.
func PricingCoverageLTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldPricingCoverage, v))
}

// PricingCoverageContains applies the Contains predicate on the "pricing_coverage" field.
func PricingCoverageContains(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContains(FieldPricingCoverage, v))
}

// PricingCoverageHasPrefix applies the HasPrefix predicate on the "pricing_coverage" field.
func PricingCoverageHasPrefix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasPrefix(FieldPricingCoverage, v))
}

// PricingCoverageHasSuffix applies the HasSuffix predicate on the "pricing_coverage" field.
func PricingCoverageHasSuffix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasSuffix(FieldPricingCoverage, v))
}

// PricingCoverageEqualFold applies the EqualFold predicate on the "pricing_coverage" field.
func PricingCoverageEqualFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEqualFold(FieldPricingCoverage, v))
}

// PricingCoverageContainsFold applies the ContainsFold predicate on the "pricing_coverage" field.
func PricingCoverageContainsFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContainsFold(FieldPricingCoverage, v))
}

// UnpricedUsageCountEQ applies the EQ predicate on the "unpriced_usage_count" field.
func UnpricedUsageCountEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldUnpricedUsageCount, v))
}

// UnpricedUsageCountNEQ applies the NEQ predicate on the "unpriced_usage_count" field.
func UnpricedUsageCountNEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldUnpricedUsageCount, v))
}

// UnpricedUsageCountIn applies the In predicate on the "unpriced_usage_count" field.
func UnpricedUsageCountIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldUnpricedUsageCount, vs...))
}

// UnpricedUsageCountNotIn applies the NotIn predicate on the "unpriced_usage_count" field.
func UnpricedUsageCountNotIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldUnpricedUsageCount, vs...))
}

// UnpricedUsageCountGT applies the GT predicate on the "unpriced_usage_count" field.
func UnpricedUsageCountGT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldUnpricedUsageCount, v))
}

// UnpricedUsageCountGTE applies the GTE predicate on the "unpriced_usage_count" field.
func UnpricedUsageCountGTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldUnpricedUsageCount, v))
}

// UnpricedUsageCountLT applies the LT predicate on the "unpriced_usage_count" field.
func UnpricedUsageCountLT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldUnpricedUsageCount, v))
}

// UnpricedUsageCountLTE applies the LTE predicate on the "unpriced_usage_count" field.
func UnpricedUsageCountLTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldUnpricedUsageCount, v))
}

// FxRateEQ applies the EQ predicate on the "fx_rate" field.
func FxRateEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldFxRate, v))
}

// FxRateNEQ applies the NEQ predicate on the "fx_rate" field.
func FxRateNEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldFxRate, v))
}

// FxRateIn applies the In predicate on the "fx_rate" field.
func FxRateIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldFxRate, vs...))
}

// FxRateNotIn applies the NotIn predicate on the "fx_rate" field.
func FxRateNotIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldFxRate, vs...))
}

// FxRateGT applies the GT predicate on the "fx_rate" field.
func FxRateGT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldFxRate, v))
}

// FxRateGTE applies the GTE predicate on the "fx_rate" field.
func FxRateGTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldFxRate, v))
}

// FxRateLT applies the LT predicate on the "fx_rate" field.
func FxRateLT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldFxRate, v))
}

// FxRateLTE applies the LTE predicate on the "fx_rate" field.
func FxRateLTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldFxRate, v))
}

// FxRateContains applies the Contains predicate on the "fx_rate" field.
func FxRateContains(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContains(FieldFxRate, v))
}

// FxRateHasPrefix applies the HasPrefix predicate on the "fx_rate" field.
func FxRateHasPrefix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasPrefix(FieldFxRate, v))
}

// FxRateHasSuffix applies the HasSuffix predicate on the "fx_rate" field.
func FxRateHasSuffix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasSuffix(FieldFxRate, v))
}

// FxRateEqualFold applies the EqualFold predicate on the "fx_rate" field.
func FxRateEqualFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEqualFold(FieldFxRate, v))
}

// FxRateContainsFold applies the ContainsFold predicate on the "fx_rate" field.
func FxRateContainsFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContainsFold(FieldFxRate, v))
}

// FormulaVersionEQ applies the EQ predicate on the "formula_version" field.
func FormulaVersionEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldFormulaVersion, v))
}

// FormulaVersionNEQ applies the NEQ predicate on the "formula_version" field.
func FormulaVersionNEQ(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldFormulaVersion, v))
}

// FormulaVersionIn applies the In predicate on the "formula_version" field.
func FormulaVersionIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldFormulaVersion, vs...))
}

// FormulaVersionNotIn applies the NotIn predicate on the "formula_version" field.
func FormulaVersionNotIn(vs ...string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldFormulaVersion, vs...))
}

// FormulaVersionGT applies the GT predicate on the "formula_version" field.
func FormulaVersionGT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldFormulaVersion, v))
}

// FormulaVersionGTE applies the GTE predicate on the "formula_version" field.
func FormulaVersionGTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldFormulaVersion, v))
}

// FormulaVersionLT applies the LT predicate on the "formula_version" field.
func FormulaVersionLT(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldFormulaVersion, v))
}

// FormulaVersionLTE applies the LTE predicate on the "formula_version" field.
func FormulaVersionLTE(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldFormulaVersion, v))
}

// FormulaVersionContains applies the Contains predicate on the "formula_version" field.
func FormulaVersionContains(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContains(FieldFormulaVersion, v))
}

// FormulaVersionHasPrefix applies the HasPrefix predicate on the "formula_version" field.
func FormulaVersionHasPrefix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasPrefix(FieldFormulaVersion, v))
}

// FormulaVersionHasSuffix applies the HasSuffix predicate on the "formula_version" field.
func FormulaVersionHasSuffix(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldHasSuffix(FieldFormulaVersion, v))
}

// FormulaVersionEqualFold applies the EqualFold predicate on the "formula_version" field.
func FormulaVersionEqualFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEqualFold(FieldFormulaVersion, v))
}

// FormulaVersionContainsFold applies the ContainsFold predicate on the "formula_version" field.
func FormulaVersionContainsFold(v string) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldContainsFold(FieldFormulaVersion, v))
}

// GeneratedByUserIDEQ applies the EQ predicate on the "generated_by_user_id" field.
func GeneratedByUserIDEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldGeneratedByUserID, v))
}

// GeneratedByUserIDNEQ applies the NEQ predicate on the "generated_by_user_id" field.
func GeneratedByUserIDNEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldGeneratedByUserID, v))
}

// GeneratedByUserIDIn applies the In predicate on the "generated_by_user_id" field.
func GeneratedByUserIDIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldGeneratedByUserID, vs...))
}

// GeneratedByUserIDNotIn applies the NotIn predicate on the "generated_by_user_id" field.
func GeneratedByUserIDNotIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldGeneratedByUserID, vs...))
}

// GeneratedByUserIDGT applies the GT predicate on the "generated_by_user_id" field.
func GeneratedByUserIDGT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldGeneratedByUserID, v))
}

// GeneratedByUserIDGTE applies the GTE predicate on the "generated_by_user_id" field.
func GeneratedByUserIDGTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldGeneratedByUserID, v))
}

// GeneratedByUserIDLT applies the LT predicate on the "generated_by_user_id" field.
func GeneratedByUserIDLT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldGeneratedByUserID, v))
}

// GeneratedByUserIDLTE applies the LTE predicate on the "generated_by_user_id" field.
func GeneratedByUserIDLTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldGeneratedByUserID, v))
}

// LockedByUserIDEQ applies the EQ predicate on the "locked_by_user_id" field.
func LockedByUserIDEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldLockedByUserID, v))
}

// LockedByUserIDNEQ applies the NEQ predicate on the "locked_by_user_id" field.
func LockedByUserIDNEQ(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldLockedByUserID, v))
}

// LockedByUserIDIn applies the In predicate on the "locked_by_user_id" field.
func LockedByUserIDIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldLockedByUserID, vs...))
}

// LockedByUserIDNotIn applies the NotIn predicate on the "locked_by_user_id" field.
func LockedByUserIDNotIn(vs ...int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldLockedByUserID, vs...))
}

// LockedByUserIDGT applies the GT predicate on the "locked_by_user_id" field.
func LockedByUserIDGT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldLockedByUserID, v))
}

// LockedByUserIDGTE applies the GTE predicate on the "locked_by_user_id" field.
func LockedByUserIDGTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldLockedByUserID, v))
}

// LockedByUserIDLT applies the LT predicate on the "locked_by_user_id" field.
func LockedByUserIDLT(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldLockedByUserID, v))
}

// LockedByUserIDLTE applies the LTE predicate on the "locked_by_user_id" field.
func LockedByUserIDLTE(v int64) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldLockedByUserID, v))
}

// LockedByUserIDIsNil applies the IsNil predicate on the "locked_by_user_id" field.
func LockedByUserIDIsNil() predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIsNull(FieldLockedByUserID))
}

// LockedByUserIDNotNil applies the NotNil predicate on the "locked_by_user_id" field.
func LockedByUserIDNotNil() predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotNull(FieldLockedByUserID))
}

// LockedAtEQ applies the EQ predicate on the "locked_at" field.
func LockedAtEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldEQ(FieldLockedAt, v))
}

// LockedAtNEQ applies the NEQ predicate on the "locked_at" field.
func LockedAtNEQ(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNEQ(FieldLockedAt, v))
}

// LockedAtIn applies the In predicate on the "locked_at" field.
func LockedAtIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIn(FieldLockedAt, vs...))
}

// LockedAtNotIn applies the NotIn predicate on the "locked_at" field.
func LockedAtNotIn(vs ...time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotIn(FieldLockedAt, vs...))
}

// LockedAtGT applies the GT predicate on the "locked_at" field.
func LockedAtGT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGT(FieldLockedAt, v))
}

// LockedAtGTE applies the GTE predicate on the "locked_at" field.
func LockedAtGTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldGTE(FieldLockedAt, v))
}

// LockedAtLT applies the LT predicate on the "locked_at" field.
func LockedAtLT(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLT(FieldLockedAt, v))
}

// LockedAtLTE applies the LTE predicate on the "locked_at" field.
func LockedAtLTE(v time.Time) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldLTE(FieldLockedAt, v))
}

// LockedAtIsNil applies the IsNil predicate on the "locked_at" field.
func LockedAtIsNil() predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldIsNull(FieldLockedAt))
}

// LockedAtNotNil applies the NotNil predicate on the "locked_at" field.
func LockedAtNotNil() predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.FieldNotNull(FieldLockedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PoolSettlement) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PoolSettlement) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PoolSettlement) predicate.PoolSettlement {
	return predicate.PoolSettlement(sql.NotPredicates(p))
}
