// Code generated by ent, DO NOT EDIT.

package accountlifecycleevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldAccountID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldEventType, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldReason, v))
}

// ReplacementAccountID applies equality check predicate on the "replacement_account_id" field. It's identical to ReplacementAccountIDEQ.
func ReplacementAccountID(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldReplacementAccountID, v))
}

// TransferredCostMinor applies equality check predicate on the "transferred_cost_minor" field. It's identical to TransferredCostMinorEQ.
func TransferredCostMinor(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldTransferredCostMinor, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldSource, v))
}

// CreatedByUserID applies equality check predicate on the "created_by_user_id" field. It's identical to CreatedByUserIDEQ.
func CreatedByUserID(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldAccountID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldContainsFold(FieldEventType, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldOccurredAt, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldContainsFold(FieldReason, v))
}

// ReplacementAccountIDEQ applies the EQ predicate on the "replacement_account_id" field.
func ReplacementAccountIDEQ(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldReplacementAccountID, v))
}

// ReplacementAccountIDNEQ applies the NEQ predicate on the "replacement_account_id" field.
func ReplacementAccountIDNEQ(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldReplacementAccountID, v))
}

// ReplacementAccountIDIn applies the In predicate on the "replacement_account_id" field.
func ReplacementAccountIDIn(vs ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldReplacementAccountID, vs...))
}

// ReplacementAccountIDNotIn applies the NotIn predicate on the "replacement_account_id" field.
func ReplacementAccountIDNotIn(vs ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldReplacementAccountID, vs...))
}

// ReplacementAccountIDGT applies the GT predicate on the "replacement_account_id" field.
func ReplacementAccountIDGT(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldReplacementAccountID, v))
}

// ReplacementAccountIDGTE applies the GTE predicate on the "replacement_account_id" field.
func ReplacementAccountIDGTE(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldReplacementAccountID, v))
}

// ReplacementAccountIDLT applies the LT predicate on the "replacement_account_id" field.
func ReplacementAccountIDLT(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldReplacementAccountID, v))
}

// ReplacementAccountIDLTE applies the LTE predicate on the "replacement_account_id" field.
func ReplacementAccountIDLTE(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldReplacementAccountID, v))
}

// ReplacementAccountIDIsNil applies the IsNil predicate on the "replacement_account_id" field.
func ReplacementAccountIDIsNil() predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIsNull(FieldReplacementAccountID))
}

// ReplacementAccountIDNotNil applies the NotNil predicate on the "replacement_account_id" field.
func ReplacementAccountIDNotNil() predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotNull(FieldReplacementAccountID))
}

// TransferredCostMinorEQ applies the EQ predicate on the "transferred_cost_minor" field.
func TransferredCostMinorEQ(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldTransferredCostMinor, v))
}

// TransferredCostMinorNEQ applies the NEQ predicate on the "transferred_cost_minor" field.
func TransferredCostMinorNEQ(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldTransferredCostMinor, v))
}

// TransferredCostMinorIn applies the In predicate on the "transferred_cost_minor" field.
func TransferredCostMinorIn(vs ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldTransferredCostMinor, vs...))
}

// TransferredCostMinorNotIn applies the NotIn predicate on the "transferred_cost_minor" field.
func TransferredCostMinorNotIn(vs ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldTransferredCostMinor, vs...))
}

// TransferredCostMinorGT applies the GT predicate on the "transferred_cost_minor" field.
func TransferredCostMinorGT(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldTransferredCostMinor, v))
}

// TransferredCostMinorGTE applies the GTE predicate on the "transferred_cost_minor" field.
func TransferredCostMinorGTE(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldTransferredCostMinor, v))
}

// TransferredCostMinorLT applies the LT predicate on the "transferred_cost_minor" field.
func TransferredCostMinorLT(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldTransferredCostMinor, v))
}

// TransferredCostMinorLTE applies the LTE predicate on the "transferred_cost_minor" field.
func TransferredCostMinorLTE(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldTransferredCostMinor, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldContainsFold(FieldSource, v))
}

// CreatedByUserIDEQ applies the EQ predicate on the "created_by_user_id" field.
func CreatedByUserIDEQ(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDNEQ applies the NEQ predicate on the "created_by_user_id" field.
func CreatedByUserIDNEQ(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDIn applies the In predicate on the "created_by_user_id" field.
func CreatedByUserIDIn(vs ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDNotIn applies the NotIn predicate on the "created_by_user_id" field.
func CreatedByUserIDNotIn(vs ...int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDGT applies the GT predicate on the "created_by_user_id" field.
func CreatedByUserIDGT(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGT(FieldCreatedByUserID, v))
}

// CreatedByUserIDGTE applies the GTE predicate on the "created_by_user_id" field.
func CreatedByUserIDGTE(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldGTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDLT applies the LT predicate on the "created_by_user_id" field.
func CreatedByUserIDLT(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLT(FieldCreatedByUserID, v))
}

// CreatedByUserIDLTE applies the LTE predicate on the "created_by_user_id" field.
func CreatedByUserIDLTE(v int64) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldLTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDIsNil applies the IsNil predicate on the "created_by_user_id" field.
func CreatedByUserIDIsNil() predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldIsNull(FieldCreatedByUserID))
}

// CreatedByUserIDNotNil applies the NotNil predicate on the "created_by_user_id" field.
func CreatedByUserIDNotNil() predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.FieldNotNull(FieldCreatedByUserID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountLifecycleEvent) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountLifecycleEvent) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountLifecycleEvent) predicate.AccountLifecycleEvent {
	return predicate.AccountLifecycleEvent(sql.NotPredicates(p))
}
