// Code generated by ent, DO NOT EDIT.

package accountcostentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountcostentry type in the database.
	Label = "account_cost_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldPayerUserID holds the string denoting the payer_user_id field in the database.
	FieldPayerUserID = "payer_user_id"
	// FieldPurchaseSourceID holds the string denoting the purchase_source_id field in the database.
	FieldPurchaseSourceID = "purchase_source_id"
	// FieldEntryType holds the string denoting the entry_type field in the database.
	FieldEntryType = "entry_type"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldOriginalAmount holds the string denoting the original_amount field in the database.
	FieldOriginalAmount = "original_amount"
	// FieldCnyAmountMinor holds the string denoting the cny_amount_minor field in the database.
	FieldCnyAmountMinor = "cny_amount_minor"
	// FieldFxRate holds the string denoting the fx_rate field in the database.
	FieldFxRate = "fx_rate"
	// FieldServiceStart holds the string denoting the service_start field in the database.
	FieldServiceStart = "service_start"
	// FieldServiceEnd holds the string denoting the service_end field in the database.
	FieldServiceEnd = "service_end"
	// FieldWarrantyEnd holds the string denoting the warranty_end field in the database.
	FieldWarrantyEnd = "warranty_end"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldPurchaseURL holds the string denoting the purchase_url field in the database.
	FieldPurchaseURL = "purchase_url"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldSupersedesID holds the string denoting the supersedes_id field in the database.
	FieldSupersedesID = "supersedes_id"
	// FieldRelatedAccountID holds the string denoting the related_account_id field in the database.
	FieldRelatedAccountID = "related_account_id"
	// FieldCreatedByUserID holds the string denoting the created_by_user_id field in the database.
	FieldCreatedByUserID = "created_by_user_id"
	// Table holds the table name of the accountcostentry in the database.
	Table = "account_cost_entries"
)

// Columns holds all SQL columns for accountcostentry fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAccountID,
	FieldPayerUserID,
	FieldPurchaseSourceID,
	FieldEntryType,
	FieldCurrency,
	FieldOriginalAmount,
	FieldCnyAmountMinor,
	FieldFxRate,
	FieldServiceStart,
	FieldServiceEnd,
	FieldWarrantyEnd,
	FieldPaidAt,
	FieldOrderNo,
	FieldPurchaseURL,
	FieldNote,
	FieldSupersedesID,
	FieldRelatedAccountID,
	FieldCreatedByUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// EntryTypeValidator is a validator for the "entry_type" field. It is called by the builders before save.
	EntryTypeValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// OriginalAmountValidator is a validator for the "original_amount" field. It is called by the builders before save.
	OriginalAmountValidator func(string) error
	// DefaultFxRate holds the default value on creation for the "fx_rate" field.
	DefaultFxRate string
	// FxRateValidator is a validator for the "fx_rate" field. It is called by the builders before save.
	FxRateValidator func(string) error
	// OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	OrderNoValidator func(string) error
	// PurchaseURLValidator is a validator for the "purchase_url" field. It is called by the builders before save.
	PurchaseURLValidator func(string) error
)

// OrderOption defines the ordering options for the AccountCostEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByPayerUserID orders the results by the payer_user_id field.
func ByPayerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayerUserID, opts...).ToFunc()
}

// ByPurchaseSourceID orders the results by the purchase_source_id field.
func ByPurchaseSourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchaseSourceID, opts...).ToFunc()
}

// ByEntryType orders the results by the entry_type field.
func ByEntryType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryType, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByOriginalAmount orders the results by the original_amount field.
func ByOriginalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalAmount, opts...).ToFunc()
}

// ByCnyAmountMinor orders the results by the cny_amount_minor field.
func ByCnyAmountMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCnyAmountMinor, opts...).ToFunc()
}

// ByFxRate orders the results by the fx_rate field.
func ByFxRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFxRate, opts...).ToFunc()
}

// ByServiceStart orders the results by the service_start field.
func ByServiceStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceStart, opts...).ToFunc()
}

// ByServiceEnd orders the results by the service_end field.
func ByServiceEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceEnd, opts...).ToFunc()
}

// ByWarrantyEnd orders the results by the warranty_end field.
func ByWarrantyEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWarrantyEnd, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByPurchaseURL orders the results by the purchase_url field.
func ByPurchaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchaseURL, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// BySupersedesID orders the results by the supersedes_id field.
func BySupersedesID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupersedesID, opts...).ToFunc()
}

// ByRelatedAccountID orders the results by the related_account_id field.
func ByRelatedAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelatedAccountID, opts...).ToFunc()
}

// ByCreatedByUserID orders the results by the created_by_user_id field.
func ByCreatedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByUserID, opts...).ToFunc()
}
